### ISSUE TITLE
Adding "networkLocalRatelimit" support on Helm chart

### ISSUE THREAD

**Issue by vivekyad4v** [kgateway-dev/kgateway#10014]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.16.4

### Kubernetes Version

1.28

### Describe the bug

Don't see an option to pass below in the Gloo helm chart - 

```
  httpGateway:
    options: 
      networkLocalRatelimit: 
        maxTokens: 1
        tokensPerFill: 1
        fillInterval: 100s
``` 

I want to enable local rate limiting at gateway level but unable to pass the desired arguments. 

Ref - 
https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/open_source_helm_chart_values/
https://docs.solo.io/gloo-edge/latest/guides/security/local_rate_limiting/http/  

Pls suggest. 

### Expected Behavior

Must have an argument supported in Helm chart for "networkLocalRateLimit".

### Steps to reproduce the bug

N/A
