### ISSUE TITLE
Add GrpcService.authority" configuration to OpenTelemetry config in Gateway Config HttpListenerOptions -> HttpConnectionManagerSettings settings

### ISSUE THREAD

**Issue by pszeto** [kgateway-dev/kgateway#10024]
# Updated Issue Description

## Context
By default, when referencing the GG ExtAuth, RateLimit and OTEL gRPC Services/endpoints, Gloo Gateway generates an Envoy configuration on which the `:authority` pseudo-header is not set/configured. In this case, Envoy will use the configured `cluster_name` as the value for this authority header. See: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice-envoygrpc

Some users however require that a different `:authority` header is sent to their ExtAuth, RateLimit and OTEL gRPC services, which requires them to be able to configure this authority header.

Both the ExtAuth and RateLimit configuration already allow users to set this configuration:
- [ExtAuth](https://docs.solo.io/gloo-edge/main/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#grpcservice)
- [RateLimit](https://docs.solo.io/gloo-edge/main/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk/#grpcservice)

However, there is no such setting for the OTEL config in the `ListenerTracingSettings` of the `HttpListenerOptions -> HttpConnectionManagerSettings`

## Requirement
The requirement is to be able to set this the `authority` configuration on the `openTelemetryConfig` in the `HttpListenerOptions`.

### Job Stories
_When I'm refering a gRPC OpenTelemetry Collector from my HttpListenerOptions,
I want to be able to configure the :authority pseudo header that is used in my gRPC requests,
So I'm able to use a gRPC OTEL Collector that expects different :authority headers than the default header provided by Gloo Gateway/Envoy_

## Resources
See also the Gloo Gateway OpenTelemetry Tracing documentation: https://docs.solo.io/gloo-edge/main/guides/observability/tracing/otel/

# Original Issue Description

### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17.0

### Is your feature request related to a problem? Please describe.

When configuring various grpc services, extauth, ratelimit, or otel, it's reference using the upstream name:

Example Extauth
```
  extauth:
    extauthzServerRef:
      name: extauth
      namespace: gloo-system
```

Example RateLimit:
```
  ratelimitServer:
    rateLimitBeforeAuth: false
    ratelimitServerRef:
      name: rate-limit
      namespace: gloo-system
```

Example Otel:
```
          openTelemetryConfig:
            collectorUpstreamRef:
              namespace: "gloo-system"
              name: "opentelemetry-collector"
```

These gets configured to the following the envoy configs:

Rate-limit
```
             {
              "name": "envoy.filters.http.ratelimit",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit",
               "domain": "ingress",
               "request_type": "both",
               "timeout": "0.100s",
               "rate_limit_service": {
                "grpc_service": {
                 "envoy_grpc": {
                  "cluster_name": "rate-limit_gloo-system"
                 }
                },
                "transport_api_version": "V3"
               }
              }
             }
```

extauth
```
             {
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "extauth_gloo-system"
                },
                "timeout": "0.200s"
               },
               "metadata_context_namespaces": [
                "envoy.filters.http.jwt_authn"
               ],
               "transport_api_version": "V3"
              }
             },
````

otel:
```
"tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 100
             },
             "overall_sampling": {
              "value": 100
             },
             "provider": {
              "name": "envoy.tracers.opentelemetry",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "opentelemetry-collector_gloo-system"
                }
               },
               "service_name": "gateway-proxy"
              }
             }
            }
```

Sometimes the backend grcp requires a different authority.  Envoy supports passing a different authority in the `config.core.v3.GrpcService.EnvoyGrpc`

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice-envoygrpc
```
{
  "cluster_name": ...,
  "authority": ...,
  "retry_policy": {...},
  "max_receive_message_length": {...},
  "skip_envoy_headers": ...
}
```

### Describe the solution you'd like

Expose an option in the upstream to specify the authority. 

For example. 

Extauth:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: extauth
  name: extauth
  namespace: gloo-system
spec:
  healthChecks:
  - grpcHealthCheck:
      serviceName: ext-auth
    healthyThreshold: 3
    interval: 10s
    noTrafficInterval: 10s
    timeout: 5s
    unhealthyThreshold: 3
  kube:
    serviceName: extauth
    serviceNamespace: gloo-system
    servicePort: 8083
    serviceSpec:
      grpc: {}
  useHttp2: true
  grpcAuthority: extauth.gloo-system.svc.cluster.local
```

and the resulting extauth will have 

extauth
```
             {
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "extauth_gloo-system"
                 "authority": "extauth.gloo-system.svc.cluster.local"
                },
                "timeout": "0.200s"
               },
               "metadata_context_namespaces": [
                "envoy.filters.http.jwt_authn"
               ],
               "transport_api_version": "V3"
              }
             },
````

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208360941975868) by [Unito](https://www.unito.io)

**Comment by jenshu** [comment]
extauth and ratelimit currently support an authority field on the grpc service settings:
- [extauth](https://github.com/solo-io/gloo/blob/027637efc040fff247d6e153bdc0e3f5f98cbb6a/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L170)
- [ratelimit](https://github.com/solo-io/gloo/blob/027637efc040fff247d6e153bdc0e3f5f98cbb6a/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto#L45)

**Comment by pszeto** [comment]
@jenshu Thanks, i just found that right now as well. It seems when configuring oTel it doesn't have it:

```
openTelemetryConfig:
            collectorUpstreamRef:
              namespace: "gloo-system"
              name: "opentelemetry-collector"
 ```

would it be better at the upstream level, so it's more generic?
