### ISSUE TITLE
Add `tolerations` to Helm values for inclusion on default `GatewayParameters`

### ISSUE THREAD

**Issue by djmcaleese** [kgateway-dev/kgateway#10412]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.18.0

### Is your feature request related to a problem? Please describe.

When installing k8sgateway I'd like the ability to provide a default set of `tolerations` to be added to my gateway proxy pods.

### Describe the solution you'd like

The Helm values should include a way to set `tolerations`, similar to how graceful shutdown and probes can be set today. Something like:

```yaml
gloo:
  kubeGateway:
    enabled: true
    gatewayParameters:
      glooGateway:
        podTemplate:
          tolerations:
          - key: "key1"
            operator: "Equal"
            value: "value1"
            effect: "NoSchedule"
```

This aligns with the structure of `GatewayParameters` which has `spec.kube.podTemplate.tolerations`.

### Describe alternatives you've considered

`spec.kube.podTemplate.tolerations` can be added after installation to the resulting default `GatewayParameters`, or to other `GatewayParameters` resources that can be opted into by individual gateways.

### Additional Context

There's [template code](https://github.com/k8sgateway/k8sgateway/blob/9e9d1ea233fec8633a83a9e0d356571694c5e9c4/install/helm/gloo/templates/43-gatewayparameters.yaml#L73-L103) to configure `podTemplate` on the default `GatewayParameters` object. This is where other useful configuration is extracted from the Helm values and added to that resource.
