### ISSUE TITLE
deploy Waypoint yaml UX issue

### ISSUE THREAD

**Issue by linsun** [kgateway-dev/kgateway#10490]
### K8sGateway Version

latest

### Is your feature request related to a problem? Please describe.

related to https://github.com/kgateway-dev/kgateway/issues/10453

When deploying a waypoint, currently, not only i have to specify the class name but also the proxy protocol and port like below:

```
  listeners:
  - name: proxy
    port: 15088
    protocol: istio.io/PROXY
```

### Describe the solution you'd like

This could be a friction for users using istio-waypoint today. Could we not requiring users to do this? 

Also, we 'd prefer consistent class name between kgateway to gloo: kgateway-waypoint, perhaps?
