### ISSUE TITLE
Improve "unknown backend kind" status condition message

### ISSUE THREAD

**Issue by timflannagan** [kgateway-dev/kgateway#10619]
When an HTTPRoute backendRef references an invalid/unsupported kind value, we should log the type that was referenced, and potentially the list of supported values. See the following for a concrete reference:

```
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2025-02-12T21:48:56Z"
        message: unknown backend kind
        observedGeneration: 6
        reason: InvalidKind
        status: "False"
        type: ResolvedRefs
      - lastTransitionTime: "2025-02-12T21:42:58Z"
```
