### ISSUE TITLE
Status messages should have a useful `message`

### ISSUE THREAD

**Issue by howardjohn** [kgateway-dev/kgateway#10780]
The status on a gateway looks like this:

```yaml
    - lastTransitionTime: "2025-03-06T15:58:01Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-03-06T15:58:01Z"
      message: ""
      observedGeneration: 1
      reason: NoConflicts
      status: "False"
      type: Conflicted
    - lastTransitionTime: "2025-03-06T15:58:01Z"
      message: ""
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-03-06T15:58:01Z"
      message: ""
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
```

Which is not super helpful.

There is an opportunity to provide useful messages even in success cases IMO. For example:

```yaml
    - lastTransitionTime: "2025-03-06T22:22:12Z"
      message: Resource accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-03-06T22:41:30Z"
      message: Resource programmed, assigned to service(s) istio-istio.istio.svc.cluster.local:80
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
```

(from Istio)
