### ISSUE TITLE
[waypoint] remove the need to specify listeners on the Gateway

### ISSUE THREAD

**Issue by stevenctl** [kgateway-dev/kgateway#10808]
```
# Deploys a kgateway Waypoint proxy.
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: httpbin-waypoint
  namespace: httpbin
spec:
  gatewayClassName: kgateway-waypoint
  listeners:
  - protocol: istio.io/PROXY
    port: 15088
    name: mesh
    allowedRoutes:
      namespaces:
        from: Same

```

We're currently requiring a listener that specifies a magic port for these Gateways. This can be optional to improve the UX, and we can make it inferred. 

Open question: if the user wants allowedRoutes, can we make protocol/port inferred?

To implement this, we'll need to update the waypoint translator and validation code for Gateway specifically for the waypoint class.
