### ISSUE TITLE
Prompt enrichment not working

### ISSUE THREAD

**Issue by eitansuez** [kgateway-dev/kgateway#10865]
### kgateway version

v2.0.0-main

### Kubernetes Version

v1.31

### Describe the bug

Similar to #10860 setup a kind cluster with an ai gateway.

here are the backend, route, and route policy in question:

```yaml
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: kgateway
  name: openai
spec:
  type: AI
  ai:
    llm:
      provider:
        openai:
          authToken:
            kind: SecretRef
            secretRef:
              name: openai
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: openai
spec:
  parentRefs:
  - name: ai-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.kgateway.dev
        kind: RoutePolicy
        name: openai
    backendRefs:
    - name: openai
      group: gateway.kgateway.dev
      kind: Backend
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: RoutePolicy
metadata:
  name: openai
spec:
  ai:
    promptEnrichment:
      prepend:
      - role: SYSTEM
        content: "Parse the unstructured text into CSV format and respond only with the CSV data."
```

### Expected Behavior

when sending this curl command:

```shell
kubectl exec deploy/curl -- curl -H content-type:application/json ai-gateway/openai --data '{
    "model": "gpt-4o-mini",
    "max_tokens": 128,
    "messages": [
      {
        "role": "user",
        "content": "Seattle, Los Angeles, and Chicago are cities in the United States. London, Paris, and Berlin are cities in Europe."
      }
    ]
  }' | jq -r '.choices[].message.content'
```

the output should be csv-formatted:

```console
City,Country
Seattle,United States
Los Angeles,United States
Chicago,United States
London,Europe
Paris,Europe
Berlin,Europe
```

### Steps to reproduce the bug

you should be able to reproduce the bug by playing [this instruqt lab](https://play.instruqt.com/manage/soloio/tracks/kgateway-ai-promptmgmt)

**Comment by timflannagan** [comment]
cc @npolshakova

**Comment by npolshakova** [comment]
Hey just tested this out and not able to reproduce:

Followed the setup in https://github.com/kgateway-dev/kgateway/pull/10745
```
kubectl apply -f - <<EOF 
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-gw-for-test
  namespace: gwtest
  annotations:
    gateway.kgateway.dev/gateway-parameters-name: kgateway-override
spec:
  gatewayClassName: kgateway
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: kgateway-override
  namespace: gwtest
spec:
  kube:
    aiExtension:
      enabled: true
      ports:
      - name: ai-monitoring
        containerPort: 9092
      env:
      - name: LOG_LEVEL
        value: DEBUG
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: accesslog
  namespace: gwtest
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gw-for-test
  accessLog:
    - fileSink:
        path: /dev/stdout
        jsonFormat:
          start_time: "%START_TIME%"
          method: "%REQ(X-ENVOY-ORIGINAL-METHOD?:METHOD)%"
          path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
          protocol: "%PROTOCOL%"
          response_code: "%RESPONSE_CODE%"
          response_flags: "%RESPONSE_FLAGS%"
          bytes_received: "%BYTES_RECEIVED%"
          bytes_sent: "%BYTES_SENT%"
          total_duration: "%DURATION%"
          resp_upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
          req_x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
          user_agent: "%REQ(USER-AGENT)%"
          request_id: "%REQ(X-REQUEST-ID)%"
          authority: "%REQ(:AUTHORITY)%"
          upstreamHost: "%UPSTREAM_HOST%"
          upstreamCluster: "%UPSTREAM_CLUSTER%"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: openai
  namespace: gwtest
spec:
  parentRefs:
    - name: http-gw-for-test
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    backendRefs:
    - name: openai
      group: gateway.kgateway.dev
      kind: Backend
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: kgateway
  name: openai
  namespace: gwtest
spec:
  type: AI
  ai:
    llm:
      provider:
        openai:
          authToken:
            kind: "SecretRef"
            secretRef:
              name: openai-secret
EOF
```

New config with prompt enrichment:
```
kubectl apply -f - <<EOF 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai
  namespace: gwtest
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gw-for-test
  rules:
  - backendRefs:
    - filters:
      - extensionRef:
          group: gateway.kgateway.dev
          kind: RoutePolicy
          name: route-test
        type: ExtensionRef
      group: gateway.kgateway.dev
      kind: Backend
      name: openai
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /openai
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: RoutePolicy
metadata:
  name: route-test
  namespace: gwtest
spec:
  ai:
    promptEnrichment:
      prepend:
      - role: SYSTEM
        content: "Parse the unstructured text into CSV format and respond only with the CSV data."
EOF
```

```
curl localhost:8080/openai -H content-type:application/json -d  '{
    "model": "gpt-4o-mini",
    "max_tokens": 128,
    "messages": [
      {
        "role": "user",
        "content": "Seattle, Los Angeles, and Chicago are cities in the United States. London, Paris, and Berlin are cities in Europe."
      }
    ]
  }' | jq -r '.choices[].message.content'



```

Response:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1022    0   766  100   256   1056    352 --:--:-- --:--:-- --:--:--  1407
City,Region
Seattle,United States
Los Angeles,United States
Chicago,United States
London,Europe
Paris,Europe
Berlin,Europe

```

@eitansuez can you compare your inputs with what I just tested? Thanks
