### ISSUE TITLE
Incorrect ClusterRole Reference

### ISSUE THREAD

**Issue by danehans** [kgateway-dev/kgateway#10880]
Currently, the ClusterRoleBinding is referencing `{{ include "kgateway.serviceAccountName" . }}` for the ClusterRole name:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kgateway.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kgateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kgateway.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
```

However, the reference should be the name of the ClusterRole and not the `serviceAccountName`. The ClusterRole name is currently hard-coded:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kgateway
...
```
