### ISSUE TITLE
When using MultiPools (for model failover), discovery of the API Key secret fails

### ISSUE THREAD

**Issue by rinormaloku** [kgateway-dev/kgateway#10902]
### kgateway version

v2.0.0-beta2

### Kubernetes Version

1.28

### Describe the bug

When using a multipool, the kgateway controller cannot find the openai secret in the example below:

```
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: openai
spec:
  type: AI
  ai:
    multipool:
      priorities:
      - pool:
        - hostOverride:
            host: model-failover.default.svc.cluster.local
            port: 80
          provider:
            openai:
              model: gpt-4o
              authToken:
                kind: SecretRef
                secretRef:
                  name: openai
      - pool:
        - hostOverride:
            host: model-failover.default.svc.cluster.local
            port: 80
          provider:
            openai:
              model: gpt-4.0-turbo
              authToken:
                kind: SecretRef
                secretRef:
                  name: openai
      - pool:
        - hostOverride:
            host: model-failover.default.svc.cluster.local
            port: 80
          provider:
            openai:
              model: gpt-3.5-turbo
              authToken:
                kind: SecretRef
                secretRef:
                  name: openai
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-failover
spec:
  selector:
    matchLabels:
      app: model-failover
  replicas: 1
  template:
    metadata:
      labels:
        app: model-failover
    spec:
      containers:
      - name: model-failover
        image: gcr.io/field-engineering-eu/model-failover:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: model-failover
  labels:
    app: model-failover
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: model-failover
---
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai
spec:
  parentRefs:
  - name: ai-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    backendRefs:
    - name: openai
      group: gateway.kgateway.dev
      kind: Backend
    retry:
      codes:
      - 429
      attempts: 3
```

This is the error:

```
{"level":"error","ts":"2025-03-20T08:26:10.550Z","caller":"backend/plugin.go:293","msg":"secret not found for openai","stacktrace":"github.com/kgateway-dev/kgateway/v2/internal/kgateway/extensions2/plugins/backend.processBackend\n\t/home/runner/work/kgateway/kgateway/internal/kgateway/extensions2/plugins/backend/plugin.go:293\ngithub.com/kgateway-dev/kgateway/v2/internal/kgateway/translator/irtranslator.(*BackendTranslator).TranslateBackend\n\t/home/runner/work/kgateway/kgateway/internal/kgateway/translator/irtranslator/backend.go:53\ngithub.com/kgateway-dev/kgateway/v2/internal/kgateway/proxy_syncer.NewPerClientEnvoyClusters.func1\n\t/home/runner/work/kgateway/kgateway/internal/kgateway/proxy_syncer/backends.go:61\nistio.io/istio/pkg/kube/krt.(*manyCollection[...]).onPrimaryInputEventLocked\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/kube/krt/collection.go:360\nistio.io/istio/pkg/kube/krt.(*manyCollection[...]).onPrimaryInputEvent\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/kube/krt/collection.go:341\nistio.io/istio/pkg/kube/krt.(*manyCollection[...]).runQueue.func1.1\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/kube/krt/collection.go:556\nistio.io/istio/pkg/queue.(*queueImpl).processNextItem\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/queue/instance.go:141\nistio.io/istio/pkg/queue.(*queueImpl).Run\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/queue/instance.go:180\nistio.io/istio/pkg/kube/krt.(*manyCollection[...]).runQueue\n\t/home/runner/go/pkg/mod/istio.io/istio@v0.0.0-20250212203644-c2ac935c5888/pkg/kube/krt/collection.go:564"}
```

### Expected Behavior

For the secret to be discovered and model failover to work.

### Steps to reproduce the bug

See the bug description
