### ISSUE TITLE
Status not updated when removed, and written for wrong parents

### ISSUE THREAD

**Issue by howardjohn** [kgateway-dev/kgateway#10967]
### kgateway version

v2.0.0-beta3

### Kubernetes Version

v1.32

### Describe the bug

I create a resource like

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-iidxvrwh
  namespace: mesh
spec:
  hostnames:
  - app-iidxvrwh.example.com
  parentRefs:
  - name: not-kgw2
    namespace: not-kgw2
  - kind: Gateway
    name: not-kgw
    namespace: not-kgw
  - name: kgateway
    namespace: kgateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: app-iidxvrwh
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /1234
```

Kgateway creates 3 status objects, one for each parent, and claims they are accepted. They cannot be accepted, since they Gateways are not kgateway Gateways.

if I manually remove the status, it remains removed until I do another write which triggers kgateway to sync it back up (to the incorrect state)

### Expected Behavior

We only write status for parents we own

### Steps to reproduce the bug

see above
