### ISSUE TITLE
AI Backend always uses TLS

### ISSUE THREAD

**Issue by rinormaloku** [kgateway-dev/kgateway#10960]
### kgateway version

2.0.0-main

### Kubernetes Version

1.28.0

### Describe the bug

When using Backend HostOverride the gateway forwards TLS traffic and cannot be configured to use plain text.

```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: openai
  namespace: default
spec:
  ai:
    multipool:
      priorities:
      - pool:
        - hostOverride:
            host: model-failover.default.svc.cluster.local
            port: 80
          provider:
            openai:
              authToken:
                kind: SecretRef
                secretRef:
                  name: openai
              model: gpt-4o
```

Note: In the above example I use multipool, but the issue still is there with only a backend.

For more details and the config dump see this slack thread: https://solo-io-corp.slack.com/archives/C085A044BHT/p1743170841204419

### Expected Behavior

Plain text traffic to port 80

### Steps to reproduce the bug

See the above backend resource
