### ISSUE TITLE
Setting body parseAs to AsJson in transformation does not take effect

### ISSUE THREAD

**Issue by zgqqiang** [kgateway-dev/kgateway#11008]
> https://github.com/kgateway-dev/kgateway/blob/8a208ce3462c4331ac694298528c2119ece3097b/internal/kgateway/extensions2/plugins/routepolicy/transformation_plugin.go#L60

What I want is to parse the body and add a certain field of the parsed body to the header, but because I need to add the header, the tt has already been set TransformationTemplate. ParseBodyBehavior=Transformationpb.TransformationTemplate. FontParse (What is the reason for this?) The parseAs configured in my body: AsJson will never take effect,

The simple modification is as follows:

	//BODY
	if t.Body == nil {
		tt.TransformationTemplate.BodyTransformation = &transformationpb.TransformationTemplate_Passthrough{
			Passthrough: &transformationpb.Passthrough{},
		}
	} else {
		if t.Body.ParseAs == v1alpha1.BodyParseBehaviorAsString {
			tt.TransformationTemplate.ParseBodyBehavior = transformationpb.TransformationTemplate_DontParse
		} else {
			tt.TransformationTemplate.ParseBodyBehavior = transformationpb.TransformationTemplate_ParseAsJson
		}
		if value := t.Body.Value; value != nil {
			hasTransform = true
			tt.TransformationTemplate.BodyTransformation = &transformationpb.TransformationTemplate_Body{
				Body: &transformationpb.InjaTemplate{
					Text: string(*value),
				},
			}
		}
	}

```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: transformation
spec:
  rateLimit:
    local:
      tokenBucket:
        fillInterval: 1m
        maxTokens: 80
        tokensPerFill: 20
  transformation:
    response:
      add:
        - name: "cons-info"
          value: '{{ xxxx.xxxx }}'
      body:
        parseAs: "AsJson"
        value: '{{ body }}'
```

The effect I want to achieve

```
transformation:
  '@type': type.googleapis.com/envoy.api.v2.filter.http.RouteTransformations
  transformations:
    - request_match:
        response_transformation:
          transformation_template:
            body:
              text: '{{ body }}'
            headers_to_append:
              - key: cons-info
                value:
                  text: ”{{ xxxx.xxxx }}“
```

Actual obtained

```
transformation:
  '@type': type.googleapis.com/envoy.api.v2.filter.http.RouteTransformations
  transformations:
    - request_match:
        response_transformation:
          transformation_template:
            body:
              text: '{{ body }}'
            parse_body_behavior: DontParse
            headers_to_append:
              - key: cons-info
                value:
                  text: "{{ xxxx.xxxx }}"
```
