### ISSUE TITLE
GW params not applied to istio-proxy container for sidecar integration

### ISSUE THREAD

**Issue by Nadine2016** [kgateway-dev/kgateway#11004]
### kgateway version

2.0.0-main

### Kubernetes Version

1.30

### Describe the bug

When enabling the Istio sidecar integration, it seems that the custom GatewayParameters are not getting applied to the `istio-proxy` container in the gateway proxy. 

1. Install Istio in sidecar mode. I am using the Gloo operator in GM https://docs.solo.io/gloo-mesh-enterprise/latest/istio/operator/install/#install which creates a revision istiod (`istiod-gloo`) 
2. Get kgateway Helm values. 
```
helm get values kgateway -n kgateway-system -o yaml > kgateway.yaml
open kgateway.yaml
```
3. Add the following. 
```
controller:
  extraEnv:
    KGW_ENABLE_ISTIO_AUTO_MTLS: true
```

4. Upgrade. 
```
helm upgrade -i --namespace kgateway-system --version v2.0.0-main kgateway oci://cr.kgateway.dev/kgateway-dev/charts/kgateway -f kgateway.yaml
```

5. Create custom GW params. 
```
kubectl apply -f- <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: custom-gw-params
  namespace: kgateway-system
spec:
  kube: 
    istio:
      istioProxyContainer:
        istioDiscoveryAddress: istiod-gloo.istio-system.svc:15012
        istioMetaClusterId: $ClUSTER_NAME
        istioMetaMeshId: $CLUSTER_NAME
EOF
```

6. Update GW
```
kubectl apply -f- <<EOF
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: custom-gw-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
EOF
```

7. Check that the http gateway proxy restarts and comes up with 3 containers. 
8. Check the logs of the istio-proxy container. they will show it is using istiod instead of istiod-gloo
```
2025-03-31T18:51:21.488003Z	warn	concurrency is set to 0, which will use a thread per CPU on the host. However, CPU limit is set lower. This is not recommended and may lead to performance issues. CPU count: 4, CPU Limit: 0.
2025-03-31T18:51:21.488349Z	info	Effective config: binaryPath: /usr/local/bin/envoy
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
proxyAdminPort: 15000
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
```

### Expected Behavior

The http gateway should come up with 3 containers and point to the correct istiod deployment.

### Steps to reproduce the bug

see above.
