### ISSUE TITLE
Add Pod Readiness Probe to the Gateway Class.

### ISSUE THREAD

**Issue by PetrMc** [kgateway-dev/kgateway#11036]
### kgateway version

2.0.0

### Is your feature request related to a problem? Please describe.

Currently there is no probes configured for kgateway pod proxies. Since there is a standard Envoy endpoint the probe can be added to the gateway-class. 

Here is the endpoint details:
```
- name: readiness_listener
  address:
    socket_address: { address: 0.0.0.0, port_value: 8082 }
  filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          ...
          route_config:
            ...
            virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                  - match:
                      path: "/ready"
```

### Describe the solution you'd like

Currently for waypoint test it's implemented via `GatewayParameters` (details in this PR https://github.com/kgateway-dev/kgateway/pull/11033) but the preposition is to integrate such probe into `kgateway` gateway class.

### Describe alternatives you've considered

alternative is to use `GatewayClass` definition to point to every gateway individually. It exists today.
