### ISSUE TITLE
Setting timeout on parent httproute leads to panic

### ISSUE THREAD

**Issue by jenshu** [kgateway-dev/kgateway#11044]
Repro steps:
```
kubectl -n kgateway-system apply -f https://raw.githubusercontent.com/kgateway-dev/kgateway.dev/main/assets/docs/examples/httpbin.yaml

kubectl apply -f- <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    hostname: example.com
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: parent-route
  namespace: kgateway-system
spec:
  parentRefs:
  - name: gw
  hostnames:
  - "example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo
    timeouts:
      request: 44s
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: child-route
      namespace: kgateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: child-route
  namespace: kgateway-system
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo/1
    backendRefs:
    - name: httpbin
      port: 8000
EOF
```

leads to:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x263dd18]

goroutine 169 [running]:
github.com/kgateway-dev/kgateway/v2/internal/kgateway/translator/irtranslator.applyRouteTimeout({0x38c16b8, 0x40012b6ed0}, 0x4001098ff0, 0x0?)
	/home/runner/work/kgateway/kgateway/internal/kgateway/translator/irtranslator/route.go:192 +0xc8
github.com/kgateway-dev/kgateway/v2/internal/kgateway/translator/irtranslator.(*httpRouteConfigurationTranslator).envoyRoutes(_, {_, _}, {_, _}, {{0x400125dd70}, {0x0}, 0x4001076780, 0x0, 0x0, ...}, ...)
	/home/runner/work/kgateway/kgateway/internal/kgateway/translator/irtranslator/route.go:136 +0x188
```

Note, we don't yet support delegation w/timeouts (see https://github.com/kgateway-dev/kgateway/issues/11043), but this shouldn't cause it to crash.
