### ISSUE TITLE
Support route delegation with timeouts

### ISSUE THREAD

**Issue by jenshu** [kgateway-dev/kgateway#11043]
We currently don't have support for inheritance of `timeouts` (or other native policy fields on HTTPRoute).
It would be good if something like this would work, where we set timeout on a parent and the children inherit it. We need to decide on what the override/merging strategy should be. See also https://github.com/kgateway-dev/kgateway/issues/10938
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    hostname: example.com
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: parent-route
  namespace: kgateway-system
spec:
  parentRefs:
  - name: gw
  hostnames:
  - "example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo
    timeouts:
      request: 44s
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: child-route
      namespace: kgateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: child-route
  namespace: kgateway-system
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo/1
    backendRefs:
    - name: httpbin
      port: 8000
```
