### ISSUE TITLE
route delegation: parentRefs not respected when inherit-parent-matcher is used

### ISSUE THREAD

**Issue by jenshu** [kgateway-dev/kgateway#11050]
For example, applying the following config,  where the child route has an invalid parentRef, still results in the routes being translated as if the parentRef were valid
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a
  namespace: a
  annotations:
    delegation.kgateway.dev/inherit-parent-matcher: "true"
spec:
  parentRefs:
  - name: invalid
    namespace: infra
    group: gateway.networking.k8s.io
    kind: HTTPRoute
  rules:
  - matches:
    - path:
        type: Exact
        value: /a/1
      method: PUT # should translate as PUT for parent example-route and GET for parent foo-route
    backendRefs:
    - name: svc-a
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /a/3
      headers:
      - type: Exact
        name: headerA
        value: valA
      queryParams:
      - type: Exact
        name: queryA
        value: valA
    backendRefs:
    - name: svc-a
      port: 8080
```
