### ISSUE TITLE
DestinationRule does not apply to ServiceEntry with inline endpoints

### ISSUE THREAD

**Issue by stevenctl** [kgateway-dev/kgateway#11099]
### kgateway version

2.0.0

### Kubernetes Version

1.32

### Describe the bug

```
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: example-se
  namespace: gwtest
spec:
  hosts:
  - se.example.com
  ports:
  - number: 80
    name: http
    protocol: TCP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:

  - address: 1.1.1.1
    locality: r1/r1z2/r1z2s4

  - address: 2.2.2.2
    locality: r1/r1z3/r1z3s4

  - address: 3.3.3.3
    locality: r2/r2z1/r2z1s1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: do-failover
  namespace: gwtest
spec:
  host: se.example.com
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7
      interval: 5m
      baseEjectionTime: 15m
    loadBalancer:
      localityLbSetting:
        failoverPriority:
        - "topology.kubernetes.io/region"
        - "topology.kubernetes.io/zone"
        - "topology.istio.io/subzone"

```

given this SE and DR, I expect the output cluster for a client in `r1z2s4` to have priorities `1`, `2` and `3` for the endpoints `1.1.1.1`, `2.2.2.2`, `3.3.3.3` respectively. Instead they're all treated as being the same priority. 

### Expected Behavior

given this SE and DR, I expect the output cluster for a client in `r1z2s4` to have priorities `1`, `2` and `3` for the endpoints `1.1.1.1`, `2.2.2.2`, `3.3.3.3` respectively. Instead they're all treated as being the same priority. 

### Steps to reproduce the bug

apply the above SE and DR (adjust locality info as needed), then check envoy config dump

### Additional Context

https://github.com/kgateway-dev/kgateway/blob/56438e54532d5a886d04efaf5adf5f0d37080a91/internal/kgateway/extensions2/plugins/serviceentry/endpoints.go#L65

this occurs because we directly call PrioritizeEndpoints without information about the client. this needs to be done per uniquely connected client
