### ISSUE TITLE
Enabling AWS NLB integration with proxy protocol v2 headers gets bad request

### ISSUE THREAD

**Issue by chenningg** [kgateway-dev/kgateway#11129]
### kgateway version

v2.0.0

### Kubernetes Version

v1.3.2

### Describe the bug

Follow the steps at: https://kgateway.dev/docs/setup/customize/aws-elb/nlb/

For gateway parameters. add the proxy protocol v2:
``` yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: custom-gw-params
  namespace: kgateway-system
spec:
  kube: 
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external" 
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing 
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

All requests to the Gateway will now result in a 400 Bad Request response. How do I enable proxy protocol v2 and make it work with kgateway for client IP preservation?

### Expected Behavior

I should be able to enable proxy protocol v2 and have the gateway work. Or some documentation to do so for client IP preservation on AWS.

### Steps to reproduce the bug

As above.

### Additional Environment Detail

Deployed via ArgoCD, running on EKS.
