### ISSUE TITLE
Comparisons of performance benchmarks under high load

### ISSUE THREAD

**Issue by neozhixuan** [kgateway-dev/kgateway#11121]
### kgateway version

v2.0.0

### Is your feature request related to a problem? Please describe.

I have set up kgateway in my Kubernetes cluster to route a request to a mock LLM service in the same namespace, with simple request and response processing from my custom external processor. When running performance tests using Locust, the latency and RPS seemed to not be very optimal (as compared to other Envoy services that I have previously tried), and I am trying to figure out the potential bottleneck, either in my set up, or in kgateway.

**Set-up**:
- Kgateway
    - 6 replicas of gateway proxy
        - requestMemory: 1000Mi
        - requestCPU: 3000m
    - 6 replicas of custom external processor
        - requestMemory: 1000Mi
        - requestCPU: 3000m
- Self-hosted-llm
    - 1 replica
    - Simply returns a OpenAI formatted response after 300ms delay.

A request will be sent to kgateway, which will be forwarded to the external processor to add a header. Then, the request will be forwarded to the self-hosted-llm. The response will be forwarded back to the external processor, to add a header, and a goroutine to send metrics to another API. The response will then be returned to kgateway.

**Locust Test Configurations and Results**:
Test 1 - 100 users, 10 spawn rate, 150 seconds duration, constant_throughput = 1 (essentially 100 RPS)
- Average Response Time: 398.32ms
- Median Response Time: 400.00ms
- 95th Percentile: 740ms
- 99th Percentile: 830ms

Test 2 - 500 users, 10 spawn rate, 150 seconds duration, constant_throughput = 1 (essentially 500 RPS)
- Average Response Time: 3255.59ms
- Median Response Time: 3500.00ms
- 95th Percentile: 4700ms
- 99th Percentile: 5900ms

Test 3 - 100 users, 10 spawn rate, 150 seconds duration, wait_time = constant of 0 seconds
- Average Response Time: 718.29ms
- Median Response Time: 730.00ms
- 95th Percentile: 930ms
- 99th Percentile: 1100ms
- Requests/Second: 128.64

Test 4 - 500 users, 10 spawn rate, 150 seconds duration, wait_time = constant of 0 seconds
- Average Response Time: 3139.22ms
- Median Response Time: 3300.00ms
- 95th Percentile: 4600ms
- 99th Percentile: 5700ms
- Requests/Second: 128.87

### Describe the solution you'd like

Does the team have any performance benchmark for me to run cross comparisons? Thank you!

### Describe alternatives you've considered

Perhaps the envoy settings within the envoy wrapper compared to default envoy settings could be limiting the throughput, but I am still looking into this

### Additional Context

The Kgateway proxy's CPU % usage is rather low, between 5-7%.

**Comment by kcbabo** [comment]
Hey there! Thanks very much for raising this topic and sharing the results you're seeing. At a high level, I can tell you that these numbers are very different from what we see in our own internal soak/perf testing (the numbers we see are significantly better). We would love to get a bit more detail on what you're testing here - can you share the config and code you're using for the end-to-end in this benchmark?

**Comment by neozhixuan** [comment]
Yes that would work, I have masked some data for personal reasons, but this is the general set-up that my performance test runs on. The locust test configurations are indicated in the tests above.

There will definitely be differences in our test results due to other logic like external processing and external calls. However, my focus would be more on the gateway not scaling too well with the increased RPS / load, although theoretically it should handle it decently. 

Thank you! The resources are indicated below.

**Kgateway-specific resources:**
```yaml
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: ai-gateway
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: ai-gateway
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: ai-gateway
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  kube:
    aiExtension:
      enabled: true
      ports:
      - name: ai-monitoring
        containerPort: 9092
      resources:
        requests:
          memory: "1000Mi"
          cpu: "3000m"
    service:
      type: ClusterIP
    deployment:
      replicas: 6
    envoyContainer:
      resources:
        requests:
          memory: "1000Mi"
          cpu: "3000m"
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: ext-proc-extension
  namespace: kgateway-system
spec:
  type: ExtProc
  extProc:
    grpcService:
      backendRef:
        name: grpc-ext-proc
        port: 9002
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: extproc
  namespace: kgateway-system
spec:
  extProc:
    extensionRef:
      name: ext-proc-extension
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-system
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  parentRefs:
    - name: ai-gateway
      namespace: kgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /self-hosted-llm
    backendRefs:
    - name: self-hosted-llm
      namespace: kgateway-system
      group: gateway.kgateway.dev
      kind: Backend
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.kgateway.dev
        kind: TrafficPolicy
        name: extproc
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /v1/chat/completions
```

**Other resources (external processor, locust deployment, self hosted llm)**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ext-proc
  namespace: kgateway-system
spec:
  replicas: 6
  selector:
    matchLabels:
      app: grpc-ext-proc
  template:
    metadata:
      labels:
        app: grpc-ext-proc
    spec:
      imagePullSecrets:
      - name: xxx
      containers:
        - name: golang-app-container
          image: xxx/xxx/xxx/xxx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 3000m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-ext-proc
  namespace: kgateway-system
  labels:
    app: grpc-ext-proc
spec:
  selector:
    app: grpc-ext-proc
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
      name: grpc
      appProtocol: TCP # to prevent istio from overriding existing TLS encryption
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-test
  namespace: kgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-test
  template:
    metadata:
      labels:
        app: locust-test
    spec:
      containers:
      - name: locust-test
        image: xxx/xxx/xxx/x:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: xxx
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: ai-kgateway
  name: self-hosted-llm
  namespace: kgateway-system
spec:
  type: Static
  static:
    hosts:
    - host: self-hosted-llm.kgateway-system.svc.cluster.local
      port: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-hosted-llm
  namespace: kgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-hosted-llm
  template:
    metadata:
      labels:
        app: self-hosted-llm
    spec:
      containers:
      - name: self-hosted-llm
        image: xxx/xxx/xxx/xxx:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: self-hosted-llm
  namespace: kgateway-system
spec:
  selector:
    app: self-hosted-llm
  ports:
    - name: tcp-8002
      protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
```


**Network settings (relaxed istio settings for development purposes)**
```yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: default
  namespace: kgateway-system
spec:
  egress:
  - hosts:
    - "*/*"
  outboundTrafficPolicy:
    mode: ALLOW_ANY
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: kgateway-system
spec:
  mtls:
    mode: PERMISSIVE
---
# External processor calling an api in another namespace
apiVersion: networking.istio.io/v1beta1 
kind: DestinationRule
metadata:
  name: outbound
  namespace: kgateway-system  # Sender's namespace
spec:
  host: xxx-api-service.xxx.svc.cluster.local # Receiver service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
