### ISSUE TITLE
TCPRoute not applied until kgateway deployment is restarted

### ISSUE THREAD

**Issue by djannot** [kgateway-dev/kgateway#11138]
### kgateway version

v2.0.0

### Kubernetes Version

v1.30.8

### Describe the bug

I apply the following configuration:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - name: httpbin
    protocol: TCP
    port: 8080
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: httpbin
  namespace: httpbin
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: TCPRoute
    namespace: kgateway-system
  to:
  - group: ""
    kind: Service
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-httpbin
  namespace: kgateway-system
spec:
  parentRefs:
  - name: tcp
    sectionName: httpbin
  rules:
  - backendRefs:
    - name: httpbin1
      namespace: httpbin
      port: 8000
```

But it's not applied until I edit the TCPRoute or restart the kgateway deployment

### Expected Behavior

The TCPRoute should be applied

### Steps to reproduce the bug

See description

### Additional Environment Detail

See description
