### ISSUE TITLE
[waypoint] support ext-auth TrafficPolicy in kgateway waypoint

### ISSUE THREAD

**Issue by AlfredoFausto** [kgateway-dev/kgateway#11140]
### kgateway version

v2.0.0

### Is your feature request related to a problem? Please describe.

When configuring a trafficpolicy this is accepted by the controller but no config is generated into the waypoint

```yaml
kind: TrafficPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.kgateway.dev/v1alpha1","kind":"TrafficPolicy","metadata":{"annotations":{},"labels":{"app":"ext-authz"},"name":"gateway-ext-auth-policy","namespace":"kgateway-system"},"spec":{"extAuth":{"extensionRef":{"name":"basic-ext-auth"}},"targetRefs":[{"group":"gateway.networking.k8s.io","kind":"HTTPRoute","name":"bookinfo-services"}]}}
    creationTimestamp: "2025-04-28T19:30:24Z"
    generation: 2
    labels:
      app: ext-authz
    name: gateway-ext-auth-policy
    namespace: kgateway-system
    resourceVersion: "3208975"
    uid: 5fc26fef-16eb-4cd5-a0ce-5e894c707182
  spec:
    extAuth:
      extensionRef:
        name: basic-ext-auth
      metadataContextNamespaces:
      - jwt
    targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: bookinfo-services
  status:
    conditions:
    - lastTransitionTime: "2025-04-28T19:30:24Z"
      message: Policy accepted
      reason: Accepted
      status: "True"
      type: Accepted
```

ext-auth only works as kgateway as ingress but could also be valuable if configured as a waypoint.
assuming a client is in the mesh and talks to the server in the mesh as well, it doesn't seem that talking to the ingress and hairpin traffic is great and instead, the waypoint should handle the ext-auth request.

**Comment by ymesika** [comment]
@AlfredoFausto I've been trying to reproduce this with `2.0.0` but in my test environment the waypoint is configured correctly (`envoy.extensions.filters.http.ext_authz.v3.ExtAuthz` is being added) and the in-mesh traffic that goes through the waypoint has the ext-authz enforced.

Can you please double-check this and/or share the exact configuration you are using for testing this? I would like to re-produce this locally.

**Comment by AlfredoFausto** [comment]
I have these objects deployed

ext-auth deployment
```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kgateway-system
  name: ext-authz
  labels:
    app: ext-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz
  template:
    metadata:
      labels:
        app: ext-authz
        app.kubernetes.io/name: ext-authz
    spec:
      containers:
      - image: gcr.io/istio-testing/ext-authz:1.25-dev
        name: ext-authz
        ports:
        - containerPort: 9000
EOF
```

ext-auth service
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  namespace: kgateway-system
  name: ext-authz
  labels:
    app: ext-authz
spec:
  ports:
  - port: 4444
    targetPort: 9000
    protocol: TCP
    appProtocol: kubernetes.io/h2c
  selector:
    app: ext-authz
EOF
```

gateway extension
```
kubectl apply -f - <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  namespace: kgateway-system
  name: basic-ext-auth
  labels:
    app: ext-authz
spec:
  type: ExtAuth
  extAuth:
    grpcService:
      backendRef:
        name: ext-authz
        port: 4444   
EOF
```

traffic policy on a route
```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  labels:
    app: ext-authz
  name: gateway-ext-auth-policy
  namespace: kgateway-system
spec:
  extAuth:
    extensionRef:
      name: basic-ext-auth
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httpbin2
```

The route exists in the httpbin namespace

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin2
  namespace: httpbin
spec:
  parentRefs:
  - name: httpbin2
    kind: Service
    group: ""
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
       - name: httpbin2
         port: 8000 
```

I cannot see the ExtAuth filter added in the route config and all the configs are accepted.

**Comment by ymesika** [comment]
@AlfredoFausto it is a configuration issue - the `TrafficPolicy` is in a different ns than the HTTPRoute targetRef that it references.

You can have the ExtAuth service on a different ns but will require `ReferenceGrant` from the extension. It's a bit tricky - here is the configuration that works for me:

### HTTPRoute
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin2
  namespace: httpbin
spec:
  parentRefs:
  - name: httpbin2
    kind: Service
    group: ""
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
       - name: httpbin2
         port: 8000 
```

### GatewayExtension
```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  namespace: httpbin
  name: basic-ext-auth
  labels:
    app: ext-authz
spec:
  type: ExtAuth
  extAuth:
    grpcService:
      backendRef:
        name: ext-authz
        namespace: kgateway-system
        port: 4444
```

### TrafficPolicy
```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  labels:
    app: ext-authz
  name: gateway-ext-auth-policy
  namespace: httpbin
spec:
  extAuth:
    extensionRef:
      name: basic-ext-auth
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httpbin2
```

### ReferenceGrant
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: reference-grant
  namespace: kgateway-system
spec:
  from:
    - group: gateway.kgateway.dev
      kind: GatewayExtension
      namespace: httpbin
  to:
    - group: ""
      kind: Service
```

cc @kgateway-dev/documentation-maintainers I think it's a common scenario and the use of `GatewayExtension` kind in a `ReferenceGrant` is not trivial. Probably worth adding this to the doc.
