### ISSUE TITLE
Gateway API Extended Feature Support

### ISSUE THREAD

**Issue by danehans** [kgateway-dev/kgateway#11142]
### kgateway version

v2.0.0

### Is your feature request related to a problem? Please describe.

Kgateway provides complete "core" feature coverage for the `GATEWAY-HTTP` Gateway API conformance profile. However, the "extended" features are being bypassed ([xref](https://github.com/kubernetes-sigs/gateway-api/blob/v1.3.0/conformance/reports/v1.2.1/kgateway/v2.0.0-report.yaml#L21-L49)).

### Describe the solution you'd like

Enable each extended conformance test and run the Gateway API conformance test suite to see which test(s) pass or fail. For each failing test, create an issue and link to this issue for tracking purposes. Add support for any missing `GATEWAY-HTTP` extended features based on priorities.

## GATEWAY-HTTP Unsupported Feature List
- [ ] GatewayHTTPListenerIsolation
- [ ] GatewayInfrastructurePropagation
- [ ] GatewayPort8080
- [ ] GatewayStaticAddresses
- [ ] HTTPRouteBackendProtocolWebSocket
- [ ] HTTPRouteBackendRequestHeaderModification
- [ ] HTTPRouteBackendTimeout
- [ ] HTTPRouteDestinationPortMatching
- [ ] HTTPRouteParentRefPort
- [ ] HTTPRouteRequestMultipleMirrors
- [ ] HTTPRouteRequestTimeout

**Comment by linsun** [comment]
This is required from API impl comparison, would love to see it prioritized.  cc @DuncanDoyle @Sodman

**Comment by timflannagan** [comment]
Updated the list of conformance features we don't currently support. Several PRs have burned down this list on main that we could potentially backport if strictly necessary.

Current list of features we don't support: `CONFORMANCE_UNSUPPORTED_FEATURES ?= -exempt-features=GatewayPort8080,GatewayStaticAddresses,GatewayHTTPListenerIsolation` for the envoy-based class.

For agw: `AGW_CONFORMANCE_UNSUPPORTED_FEATURES ?= -exempt-features=GatewayStaticAddresses`.

**Comment by timflannagan** [comment]
GatewayPort8080 - https://github.com/kgateway-dev/kgateway/pull/12778

GatewayHTTPListenerIsolation - looked into this earlier today, requires a deeper dive.

GatewayStaticAddresses - neither DP supports this conformance test. regardless of how valuable this feature is, likely requires deployer work that can be re-used by agw. still needs further investigation though

**Comment by davidjumani** [comment]
Running https://github.com/kgateway-dev/kgateway/commit/6ec9b5e8ea1bdb86190a3f71fcbf3ac9a5fe4009 (16-01-2026) the following features are unsupported against v1.4.1 :
- GATEWAY-GRPC
  - GatewayHTTPListenerIsolation     (envoy)
- GATEWAY-TLS
  - GatewayHTTPListenerIsolation     (envoy)
- GATEWAY-HTTP
  - GatewayHTTPListenerIsolation     (envoy)  
  - BackendTLSPolicy                         (envoy, agw)
  - BackendTLSPolicySANValidation  (envoy, agw)

**Comment by cfi2017** [comment]
From what I can tell TLSRoute termination is also part of extended conformance as described in https://gateway-api.sigs.k8s.io/guides/tls/#clientserver-and-tls

TCPRoute termination on a TLS listener was closed as part of #12906  but this does not address this conformance as this addresses TCPRoutes, not TLSRoutes, which means the behavior deviates from the expected behavior and SNI is not supported. 

related: #13397

**Comment by danehans** [comment]
The following is the list of unsupported extended features from [the most recent conformance report](https://github.com/kubernetes-sigs/gateway-api/pull/4703/changes) (GW API v1.5.1 and kgateway v2.3.0-beta.3):
```yaml
name: GATEWAY-HTTP
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-GRPC
     unsupportedFeatures:
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
  name: GATEWAY-TLS
     unsupportedFeatures:
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
```

PRs related to resolving the conformance gaps:
- https://github.com/kgateway-dev/kgateway/pull/13705 (GatewayBackendClientCertificate)
- https://github.com/kgateway-dev/kgateway/pull/13721 (GatewayHTTPSListenerDetectMisdirectedRequests)

Note that the following tests have graduated from extended to standard:
- GatewayHTTPListenerIsolation
- GatewayStaticAddresses
