### ISSUE TITLE
TrafficPolicy status does not indicate missing targetRef

### ISSUE THREAD

**Issue by ymesika** [kgateway-dev/kgateway#11160]
### kgateway version

main

### Kubernetes Version

1.31.0

### Describe the bug

When applying a `TrafficPolicy` that references a non-existing target (e.g. HTTPRoute) the status of the resource isn't updated and the controller doesn't have any logging for this case.

Also, if the target ref resource is removed, the status is still in a state of Accepted with no indication of a missing target ref.

### Expected Behavior

Status should mention that the spec's targetRef(s) does not exist.

### Steps to reproduce the bug

1. Apply a `TrafficPolicy` with a targetRef that does not exists. I had this for instance:
```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: kgateway-test
  name: gw-policy
spec:
  targetRefs:  
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: simple-route
  extAuth:
    extensionRef: 
      name: basic-extauth
```

2. After adding the missing `HTTPRoute` and verifying that the TrafficPolicy's status is updated, remove the HTTPRoute. You'll notice that status stays as it was.
