### ISSUE TITLE
OpenTelemetry Tracing Support

### ISSUE THREAD

**Issue by npolshakova** [kgateway-dev/kgateway#11173]
### kgateway version

main

### Is your feature request related to a problem? Please describe.

Envoy’s supports different end-to-end tracing capabilities to obtain visibility and track requests as they pass through the API gateway to distributed backends, such as services, databases, or other endpoints. Enable [OpenTelemetry](https://opentelemetry.io/) (OTel) tracing capabilities to obtain visibility and track requests as they pass through the API gateway.

OTel provides a standardized protocol for reporting traces, and a standardized collector through which to receive metrics. Additionally, OTel supports exporting metrics to several types of distributed tracing platforms. For the full list of supported platforms, see the [OTel GitHub repository](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter).

To trace a request, data must be captured from the moment the request is initiated and every time the request is forwarded to another endpoint, or when other microservices are called along the way. When a request is initiated, a trace ID and an initial span (parent span) are created. A span represents an operation that is performed on your request, such as an API call, a database lookup, or a call to an external service. If a request is sent to a service, a child span is created in the trace, capturing all the operations that are performed within the service.

Each operation and span is documented with a timestamp so that you can easily see how long a request was processed by a specific endpoint in your trace. Most tracing platforms have support to visualize the tracing information in a graph so that a user can easily see bottlenecks in the microservices stack.

### Describe the solution you'd like

A user should be able to configure a simple tracing config  for a Gateway's `httpConnectionManagerSettings` via the kgateway APIs: 

```yaml
    options:
      httpConnectionManagerSettings:
        tracing:
          openTelemetryConfig:
            targetRef:
              namespace: "kgateway-system"
              name: "otel-collector"
              kind: Service
```

This should result in envoy config:
```yaml
tracing
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      '@type': type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      grpc_service:
        envoy_grpc:
          cluster_name: otel-collector-otlp-grpc_kgateway-system
```

Use a tracing platform ([Zipkin](https://zipkin.io/), [Jaeger](https://www.jaegertracing.io/), [Datadog](https://docs.datadoghq.com/getting_started/tracing/), etc.) to set up tracing with OTel. 

Additionally supporting the different [OpenTelemetry Resource Detectors](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/opentelemetry/resource_detectors) would allow configuring the OTel [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.24.0/specification/overview.md#resources), an immutable representation of the entity producing telemetry as [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.24.0/specification/common/README.md#attribute). 

For example, using the EnvironmentResourceDetectorConfig would result in Envoy config that should look something like this:
```yaml
tracing
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
       grpc_service:
         envoy_grpc:
           cluster_name: otel-collector-otlp-grpc_kgateway-system
       service_name: tag-envoy
       resource_detectors:
         - name: envoy.tracers.opentelemetry.resource_detectors.environment
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.tracers.opentelemetry.resource_detectors.v3.EnvironmentResourceDetectorConfig

```

### Additional Context

Related issues:
- https://github.com/kgateway-dev/kgateway/issues/9267 
- https://github.com/kgateway-dev/kgateway/issues/10145

References:
- Upstream OpenTelemetry tracer proto: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto.html
- Upstream issue https://github.com/envoyproxy/envoy/issues/24672
