### ISSUE TITLE
`hostOverride` setting causes incorrect requests in AI Gateway

### ISSUE THREAD

**Issue by zhengkezhou1** [kgateway-dev/kgateway#11225]
### kgateway version

v1.2.1

### Kubernetes Version

kind@v0.27.0

### Describe the bug

I am exploring AiGateway and in the [configure an LLM provider](https://kgateway.dev/docs/ai/auth/#api-key) step, I want to use [Openrouter](https://openrouter.ai/docs/quickstart#using-the-openrouter-api-directly) instead of directly using OpenAI. From [EP-10494: Add Support for AI Gateway APIs](https://github.com/kgateway-dev/kgateway/blob/13a286a58f711a149df113b6256508b161f3836e/design/10494.md#supported-llm-providers), I learned about using proxy requests:

```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: ai-kgateway
  name: openrouter
  namespace: kgateway-system
spec:
  type: AI
  ai:
    llm:
      hostOverride:
        host: openrouter.ai
        port: 443
      provider:
        openai:
          model: gpt-4o
          authToken:
            kind: SecretRef
            secretRef:
              name: openrouter-secret
````

`HTTPRoute` is as follows:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openrouter
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  parentRefs:
    - name: ai-gateway
      namespace: kgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /api/v1/chat/completions
    backendRefs:
    - name: openrouter
      namespace: kgateway-system
      group: gateway.kgateway.dev
      kind: Backend
```

It is not actually requesting the openrouter API, and `content-type: text/html` has the same issue when using `llama`.

```text
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
* Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> POST /openai HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 133
>
* upload completely sent off: 133 bytes
< HTTP/1.1 200 OK
< date: Fri, 16 May 2025 14:13:53 GMT
< content-type: text/html; charset=utf-8
< cache-control: private, no-cache, no-store, max-age=0, must-revalidate
```

### Expected Behavior

`content-type: text/html; charset=utf-8` should be `Content-Type: application/json` 

### Steps to reproduce the bug

1. Use follow config.
```
apiVersion: v1
kind: Secret
metadata:
  name: openrouter-secret
  namespace: kgateway-system
  labels:
    app: ai-kgateway
type: Opaque
stringData:
  Authorization: 

---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: ai-kgateway
  name: openrouter
  namespace: kgateway-system
spec:
  type: AI
  ai:
    llm:
      hostOverride:
        host: openrouter.ai
        port: 443
      provider:
        openai:
          model: gpt-4o
          authToken:
            kind: SecretRef
            secretRef:
              name: openrouter-secret

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openrouter
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  parentRefs:
    - name: ai-gateway
      namespace: kgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /api/v1/chat/completions
    backendRefs:
    - name: openrouter
      namespace: kgateway-system
      group: gateway.kgateway.dev
      kind: Backend
```

2. sent follow request
```
 curl -v "localhost:8080/openai" \
  -H "Content-Type: application/json" \
  -d '{
  "model": "openai/gpt-4o",
  "messages": [
    {
      "role": "user",
      "content": "What is the meaning of life?"
    }
  ]
}'
```

### Additional Context

<img width="1371" alt="Image" src="https://github.com/user-attachments/assets/fb2b0fb2-57c3-48a7-ad5f-3c363871a1fb" />

**Comment by haoqixu** [comment]
This is because the `openai` LLM provider always replaces the full path with the hard-coded `/v1/chat/completions`. I think we need an option to allow users to specify the path.

**Comment by zhengkezhou1** [comment]
Yeah, but i found Ollama works fine.

**Comment by npolshakova** [comment]
Have you tried doing the path replacement to match OpenRouter's expected `/api/v1` route?
```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  labels:
    app: ai-kgateway
  name: openrouter
  namespace: kgateway-system
spec:
  type: AI
  ai:
    llm:
      hostOverride:
        host: openrouter.ai
        port: 443
      provider:
        openai:
          model: gpt-4o
          authToken:
            kind: SecretRef
            secretRef:
              name: openrouter-secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openrouter
  namespace: kgateway-system
  labels:
    app: ai-kgateway
spec:
  parentRefs:
    - name: ai-gateway
      namespace: kgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /openai
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /api/v1
    backendRefs:
    - name: openrouter
      namespace: kgateway-system
      group: gateway.kgateway.dev
      kind: Backend
```
