### ISSUE TITLE
InferencePool Backends not being "Found"

### ISSUE THREAD

**Issue by arsenetar** [kgateway-dev/kgateway#11239]
### kgateway version

v2.0.1

### Kubernetes Version

v1.32.1

### Describe the bug

When using InferencePools as the backendRef in an HTTPRoute the HTTPRoute will report the backend reference status as `BackendNotFound`, however the InferencePool will exist.  This makes the InferencePool unable to be used as a backend.

### Expected Behavior

In version v2.0.0 this works as expected and the InferencePool is able to be used as a backend for an HTTPRoute.

### Steps to reproduce the bug

Create a InferencePool such as:

``` yaml
 metadata:
  name: meta-llama-llama-3-2-3b-instruct-inference-pool
 spec:
    extensionRef:
      failureMode: FailClose
      group: ""
      kind: Service
      name: meta-llama-llama-3-2-3b-instruct-epp-service
    selector:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
    targetPortNumber: 8000
```

Create a matching HTTP route with a InferencePool backend such as:

``` yaml
    - backendRefs:
      - group: inference.networking.x-k8s.io
        kind: InferencePool
        name: meta-llama-llama-3-2-3b-instruct-inference-pool
        port: 8000
        weight: 1
```

Observe that the status of the HTTPRoute will report the InferencePool as `BackendNotFound`.  Downgrade to kgateway v2.0.0, observe it now functions correctly.

### Additional Context

This seems to be a result of this change here: https://github.com/kgateway-dev/kgateway/pull/11035/files, which removed the port when pulling in the InferencePools.

This causes https://github.com/kgateway-dev/kgateway/blob/ff335069eec3b0b44056e82d8059435e06a9a32f/internal/kgateway/krtcollections/policy.go#L158 to not find the matching pool as the key has the port portion set to `0` so the `FetchOne` does not match any of the availableBackends. 

HTTP Route snippet:
``` yaml
    - backendRefs:
      - group: inference.networking.x-k8s.io
        kind: InferencePool
        name: meta-llama-llama-3-2-3b-instruct-inference-pool
        port: 8000
        weight: 1
```

Inference pool Spec
```
 spec:
    extensionRef:
      failureMode: FailClose
      group: ""
      kind: Service
      name: meta-llama-llama-3-2-3b-instruct-epp-service
    selector:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
    targetPortNumber: 8000
```

This is an issue with the current code as well in the main branch.
