### ISSUE TITLE
Cipher Suite Config

### ISSUE THREAD

**Issue by Sodman** [kgateway-dev/kgateway#11232]
Support configuring Cipher Suites. This can be configured within the existing k8s Gateway spec.

Can use a similar mechanism to that was used for [this issue](https://github.com/solo-io/gloo/pull/10553):

`Gateway.spec.listeners.tls.options

**Comment by DuncanDoyle** [comment]
@Sodman I think we need an issue that covers most/all of the configuration options we have in GE [SSL.proto](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk/)

We've implemented quite a few of those in K8S GW API in Gloo Gateway 1.18 and 1.19:
- oneWayTls: https://github.com/kgateway-dev/kgateway/issues/10169
- alpnProtocols: https://github.com/kgateway-dev/kgateway/issues/10418
- cipher suites: https://github.com/solo-io/solo-projects/issues/7505

I think the [linked issue](https://github.com/solo-io/gloo/pull/10553) implemented a few of them, but not sure if it included `oneWayTls` and `alpnProtocols`.

**Comment by lgadban** [comment]
we need to expose the broader set of SSL/TLS config for listeners beyond cipher suites

**Comment by JohnMaddison** [comment]
+1 for needing this feature. I didn't find an equivalent to setting to how ingress-nginx does it. Which is the only thing I found so far blocking migration to kgateway for us.

ingress-nginx Example:
` nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"`


This is how Contour does it:

```
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
spec:
  envoy:
  runtimeSettings:
    envoy:
      logging:
        accessLogFormat: json
        accessLogLevel: info
      timeouts:
        connectTimeout: "30s"
        streamIdleTimeout: "90s"
      listener:
        tls:
          minimumProtocolVersion: "1.2"
          maximumProtocolVersion: "1.3"
          cipherSuites:
            - "ECDHE-ECDSA-AES128-GCM-SHA256"
            - "ECDHE-ECDSA-AES256-GCM-SHA384"
            - "AES128-GCM-SHA256"
            - "AES256-GCM-SHA384"
            - "ECDHE-RSA-AES128-GCM-SHA256"
            - "ECDHE-RSA-AES256-GCM-SHA384"
```

Maybe we could do something similar in GatewayParameters ?

**Comment by puertomontt** [comment]
Hello @JohnMaddison . We've implemented TLS extensions in https://github.com/kgateway-dev/kgateway/pull/12917 that allow you to set cipher suites using the TLS options. For example, see https://github.com/kgateway-dev/kgateway/blob/main/internal/kgateway/translator/gateway/testutils/inputs/gateway-only/tls-alpn.yaml#L15

**Comment by DuncanDoyle** [comment]
The referenced file does not exist anymore. This is the example configuration:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: kgateway
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        kgateway.dev/alpn-protocols: "h2"
        kgateway.dev/cipher-suites: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        kgateway.dev/ecdh-curves: "X25519MLKEM768,X25519,P-256"
        kgateway.dev/min-tls-version: "1.2"
        kgateway.dev/max-tls-version: "1.3"
        # TODO: add verify subject alt names https://github.com/kgateway-dev/kgateway/issues/12955
      certificateRefs:
        - name: https
          kind: Secret
```
