### ISSUE TITLE
TrafficPolicy with ExtProc causes panic

### ISSUE THREAD

**Issue by arsenetar** [kgateway-dev/kgateway#11294]
### kgateway version

v2.0.2

### Kubernetes Version

v1.32.1

### Describe the bug

A traffic policy with only an ExtProc seems to cause panics, additionally when it does have an extAuth as well the extProc never seems to be called.

### Expected Behavior

Configures the ExtProc correctly without panic in the controller.

### Steps to reproduce the bug

Encountered this bug after removing an ExtAuth entry in a traffic policy after noticing the ExtProc was not being called.  Example yaml:

``` yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: test-ai-gateway
spec:
  extProc:
    extensionRef:
      name: test-ai-gateway-ext-proc
    processingMode:
      requestBodyMode: STREAMED
      requestHeaderMode: SEND
      requestTrailerMode: SKIP
      responseBodyMode: STREAMED
      responseHeaderMode: SEND
      responseTrailerMode: SKIP
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: test-ai-gateway
```

### Additional Context

After looking into the panic the issue seems to come from https://github.com/kgateway-dev/kgateway/blob/3473a871ff59e2bbb92cff51d87aacfed970603e/internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go#L411

As the code for the ExtProc is referencing the ExtAuth instead incorrectly.  The following would seem to be the correct patch against 2.0.2.

```
diff --git a/internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go b/internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
index e800ef83f..63e024370 100644
--- a/internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
+++ b/internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
@@ -408,12 +408,12 @@ func (p *trafficPolicyPluginGwPass) ApplyListenerPlugin(ctx context.Context, pCt
 		}
 	}
 	if policy.spec.ExtProc != nil && policy.spec.ExtProc.provider != nil {
-		if p.extAuthPerProvider == nil {
-			p.extAuthPerProvider = make(map[string]providerWithFromListener)
+		if p.extProcPerProvider == nil {
+			p.extProcPerProvider = make(map[string]providerWithFromListener)
 		}
-		k := policy.spec.extAuth.provider.ResourceName()
-		p.extAuthPerProvider[k] = providerWithFromListener{
-			provider:     policy.spec.extAuth.provider,
+		k := policy.spec.ExtProc.provider.ResourceName()
+		p.extProcPerProvider[k] = providerWithFromListener{
+			provider:     policy.spec.ExtProc.provider,
 			fromListener: true,
 		}
 	}
```
