### ISSUE TITLE
ExtProc trafficPolicy does not appear to set ProcessingMode

### ISSUE THREAD

**Issue by arsenetar** [kgateway-dev/kgateway#11301]
### kgateway version

v2.0.2

### Kubernetes Version

v1.32.1

### Describe the bug

When trying to configure the ProcessingMode of an extProc filter (to do some request/response body processing for example) the configuration set in envoy is not updated (aka uses the defaults).  It appears when debugging only the grpcService propogates down (checked via envoy config dump).  This doesn't seem to have any difference if the trafficpolicy is attached to a Gateway or an HTTPRoute.

### Expected Behavior

Configuration of ProcessingMode in the CR propagates into the envoy configuration when attached to a Gateway or specific HTTPRoutes.

### Steps to reproduce the bug

1. Create a valid ExtProc `GatewayExtension`
2. Create a Gateway and at least one corresponding HTTPRoute
3. Create a TrafficPolicy similar to the below (using correct Refs for 1 & 2), example shows using the Gateway:

``` yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: test-gateway
spec:
  extProc:
    extensionRef:
      name: test-ai-gateway-ext-proc
    processingMode:
      requestBodyMode: STREAMED
      requestHeaderMode: SEND
      requestTrailerMode: SEND
      responseBodyMode: STREAMED
      responseHeaderMode: SEND
      responseTrailerMode: SEND
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: test-gateway
```

4. Dump the envoy config and see that it only configured the grpcservice in the httpfilters.  Additional can debug into the kgateway code and see that it did not process this fully.

### Additional Context

Seems like the processingMode is not set on the provider returned in https://github.com/kgateway-dev/kgateway/blob/3473a871ff59e2bbb92cff51d87aacfed970603e/internal/kgateway/extensions2/plugins/routepolicy/extproc_policy.go#L16 and instead only put into the ExtProcPerRoute overrides, which don't seem to be used later.
