### ISSUE TITLE
Failed to update HTTPRoute status for invalid path prefix matcher

### ISSUE THREAD

**Issue by timflannagan** [kgateway-dev/kgateway#11314]
### kgateway version

main

### Kubernetes Version

N/A

### Describe the bug

When deploying an HTTPRoute with a configuration that's known to be invalid, kgateway cannot successfully update the status of this resource to community this issue:

```
{"time":"2025-05-30T10:35:30.561610839Z","level":"ERROR","msg":"all attempts failed at updating HTTPRoute status","component":"proxy_syncer","subcomponent":"routeStatusSyncer","error":"All attempts fail:\n#1: HTTPRoute.gateway.networking.k8s.io \"invalid-traffic-policy-route\" is invalid: status.parents[0].conditions[0].reason: Invalid value: \"error listener~8080~www_example_com-route-0-httproute-invalid-traffic-policy-route-gwtest-0-0-matcher-0: the rewrite /new//../path is invalid: path [/new//../path] cannot contain [//]\": parents[0].conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'\n#2: HTTPRoute.gateway.networking.k8s.io \"invalid-traffic-policy-route\" is invalid: status.parents[0].conditions[0].reason: Invalid value: \"error listener~8080~www_example_com-route-0-httproute-invalid-traffic-policy-route-gwtest-0-0-matcher-0: the rewrite /new//../path is invalid: path [/new//../path] cannot contain [//]\": parents[0].conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'\n#3: HTTPRoute.gateway.networking.k8s.io \"invalid-traffic-policy-route\" is invalid: status.parents[0].conditions[0].reason: Invalid value: \"error listener~8080~www_example_com-route-0-httproute-invalid-traffic-policy-route-gwtest-0-0-matcher-0: the rewrite /new//../path is invalid: path [/new//../path] cannot contain [//]\": parents[0].conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'\n#4: HTTPRoute.gateway.networking.k8s.io \"invalid-traffic-policy-route\" is invalid: status.parents[0].conditions[0].reason: Invalid value: \"error listener~8080~www_example_com-route-0-httproute-invalid-traffic-policy-route-gwtest-0-0-matcher-0: the rewrite /new//../path is invalid: path [/new//../path] cannot contain [//]\": parents[0].conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'\n#5: HTTPRoute.gateway.networking.k8s.io \"invalid-traffic-policy-route\" is invalid: status.parents[0].conditions[0].reason: Invalid value: \"error listener~8080~www_example_com-route-0-httproute-invalid-traffic-policy-route-gwtest-0-0-matcher-0: the rewrite /new//../path is invalid: path [/new//../path] cannot contain [//]\": parents[0].conditions[0].reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'","route":{"Namespace":"gwtest","Name":"invalid-traffic-policy-route"}}
```

This is because the HTTP route rule translator is using the error as the status condition reason in the PartiallyInvalid type. See https://github.com/kgateway-dev/kgateway/blob/ad1a8cdd44674495cad92b5f17c531bc6bff5489/internal/kgateway/translator/irtranslator/route.go#L183.

### Expected Behavior

Status is properly set and written back to the problematic CR

### Steps to reproduce the bug

Apply the following config:

<details>

```yaml
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-gw-for-test
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: gwtest
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: reviews
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: reviews-slice
  namespace: gwtest
  labels:
    kubernetes.io/service-name: reviews
    app: reviews
    service: reviews
addressType: IPv4
endpoints:
  - addresses:
      - 10.244.1.11
    conditions:
      ready: true
    nodeName: worker
    targetRef:
      kind: Pod
      name: reviews-1
      namespace: gwtest
ports:
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: invalid-traffic-policy-route
  namespace: gwtest
spec:
  parentRefs:
    - name: http-gw-for-test
      namespace: gwtest
  hostnames:
    - "www.example.com"
  rules:
  - backendRefs:
      - name: reviews
        port: 8080
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /new//../path
```

</details>

Validate the expected log is present in the kgateway deployment 

### Additional Environment Detail

Behavior is also reproducible if a policy plugin returns an error in the ApplyForRoute method.
