### ISSUE TITLE
Track observed generation in policy status

### ISSUE THREAD

**Issue by timflannagan** [kgateway-dev/kgateway#11386]
### kgateway version

main

### Kubernetes Version

N/A

### Describe the bug

When creating a valid TrafficPolicy CR, the status is reporting as accepted, but the ancestor status conditions lack the observed generation field:

```
status:
  ancestors:
  - ancestorRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gw-for-test
      namespace: gwtest
    conditions:
    - lastTransitionTime: "2025-06-12T03:55:53Z"
      message: Policy accepted
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: kgateway.dev/kgateway
```

Related to https://github.com/kgateway-dev/kgateway/issues/10625

### Expected Behavior

Implement observed generation for policy status reporting

### Steps to reproduce the bug

1. `make run`
2. `k apply -f internal/kgateway/setup/testdata/standard/routeoptions.yaml`
3. `k get trafficpolicy -A -oyaml`
