### ISSUE TITLE
Error create gateway resource with private registry

### ISSUE THREAD

**Issue by maruco91cp1** [kgateway-dev/kgateway#11419]
### kgateway version

v2.0.2

### Kubernetes Version

v1.32.2

### Describe the bug

I am building KGateway using Helm. I am using a private registry. We configured the values.yaml file of the KGateway Helm chart with:
```
imagePullSecrets:
- name: regcred
```
When I run the Helm , KGateway deploys successfully. However, when I create a Gateway resource, the system tries to create a Deployment and fails with the following error:
**Failed to pull image "nexus.digital.vn/kgateway-dev/envoy-wrapper:v2.0.2": failed to pull and unpack image "nexus.digital.vn/kgateway-dev/envoy-wrapper:v2.0.2": failed to resolve reference "nexus.digital.vn/kgateway-dev/envoy-wrapper:v2.0.2": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials**

### Expected Behavior

resource create success use imagePullSecrets

### Steps to reproduce the bug

B1: create helm kgateway-crds
B2:  create helm kgateway
file vaules:
```
imagePullSecrets:
- name: regcred
nameOverride: kgateway

fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
deploymentAnnotations: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
controller:
  replicaCount: 1
  logLevel: info
  image:
    registry: ""
    repository: kgateway
    pullPolicy: ""
    tag: ""
  service:
    type: NodePort
    ports:
      grpc: 9977
      health: 9093
  extraEnv: {}
image:
  registry: nexus.digital.vn/kgateway-dev
  tag: "v2.0.2"
  pullPolicy: IfNotPresent
inferenceExtension:
  enabled: false
  autoProvision: false
discoveryNamespaceSelectors: []
agentGateway:
  enabled: false
```
B3: create gateway:
```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
```

**Comment by puertomontt** [comment]
I think this currently requires using a custom GatewayParameters, eg
```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: default-gateway-parameters
spec:
  kube:
    podTemplate:
      imagePullSecrets:
        - name: regcred
``` 
reference in Gateway
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: default-gateway-parameters
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: All 
```
