### ISSUE TITLE
[UX] Non-trivial missing ReferenceGrant with GatewayExtension

### ISSUE THREAD

**Issue by ymesika** [kgateway-dev/kgateway#11439]
In [a setup](https://github.com/kgateway-dev/kgateway/issues/11140#issuecomment-2975533056) where I have ext-auth service in one namespace and the `GatewayExtension` in another, the `TrafficPolicy` ends up with the following status error about a missing reference grant:

```
message: 'extauthz: failed to resolve ExtAuth backend: missing reference grant'
```

However, to resolve this one needs to create a `ReferenceGrant` but the `from` field is non-trivial because it expects it to be the `GatewayExtension`:

```yaml
spec:
  from:
    - group: gateway.kgateway.dev
      kind: GatewayExtension
      namespace: httpbin
  to:
    - group: ""
      kind: Service
```

Could be nice to have more information in the error to indicate that it's the `GatewayExtension` that needs to be added as the `from` in it.
