### ISSUE TITLE
[UX] No status for missing/misconfigured TrafficPolicy targetRef

### ISSUE THREAD

**Issue by ymesika** [kgateway-dev/kgateway#11438]
When applying the following policy to the `kgateway-test` ns while the targetRef `httpbin2` is in a different ns (or does not exists) there is no indication or status in the CR that can hint about it.

```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  labels:
    app: ext-authz
  name: gateway-ext-auth-policy
  namespace: kgateway-test
spec:
  extAuth:
    extensionRef:
      name: basic-ext-auth
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httpbin2
```

Can this be reported in a status?
