### ISSUE TITLE
Fix workflow triggers on the action_lint.yaml workflow

### ISSUE THREAD

**Issue by timflannagan** [kgateway-dev/kgateway#11488]
The action_lint.yaml workflow is currently triggered whenever a YAML file within the .github directory has been modified:

```
name: pr-github-workflow-lint

on:
  pull_request:
    paths:
      - .github/*.yaml
      - .github/*.yml
permissions:
  contents: read
```

Given this job isn't required, we risk the chance silently breaking this action, regressing main, and the result is that PRs that touch the .github/ directory fail this action regardless of whether they are related to linting failures.
