### ISSUE TITLE
[AI] Encoding issues when using YAML block scalars in `promptEnrichment`

### ISSUE THREAD

**Issue by onematchfox** [kgateway-dev/kgateway#11489]
### kgateway version

v2.0.2

### Kubernetes Version

v1.32.4

### Describe the bug

Found a couple of issues when trying to make use of YAML block scalars to set a multi-line system prompt in an AI gateway. 

1. If the block contains a "##" (markdown heading level 2), the related Envoy configuration will fail to be applied and the ai-gateway pods will spam with the following error: `[warning][config] [external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Failed to parse request template: Failed to parse merge_body_key template for key: (messages)`
2. When removing the markdown heading above, Envoy configuration will be applied successfully but any requests will fail with the error: `bad request: [json.exception.parse_error.101] parse error at line 2, column 0: syntax error while parsing value - invalid string: control character U+000A (LF) must be escaped to \u000A or \n; last read: '"# My Helpful Agent<U+000A>'`

### Expected Behavior

One should be able to configure prompt enrichment using YAML block scalars with the text containing multi-line markdown.

### Steps to reproduce the bug

1. [Setup AI gateway](https://kgateway.dev/docs/ai/setup/) and [authenticate to the LLM](https://kgateway.dev/docs/ai/auth/) as per the docs
2. kubectl apply:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai
  namespace: kgateway-system
spec:
  parentRefs:
    - name: ai-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /openai
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /v1/chat/completions
        - type: ExtensionRef
          extensionRef:
            group: gateway.kgateway.dev
            kind: TrafficPolicy
            name: openai-system-prompt
      backendRefs:
        - name: openai
          group: gateway.kgateway.dev
          kind: Backend
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: openai-system-prompt
  namespace: kgateway-system
spec:
  ai:
    promptEnrichment:
      prepend:
        - role: SYSTEM
          content: |
            # My Helpful Agent

            You are a bot that is supposed to help people.

            ## Instructions

            - Be nice
            - Do other stuff
```

3. Observe warning logs in `ai-gateway` pod
4. Send a request to the LLM provider API (see docs linked above) and observe `404` response indicating that the Envoy configuration was not applied
5. kubectl apply following traffic policy instead
```yaml
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: openai-system-prompt
  namespace: kgateway-system
spec:
  ai:
    promptEnrichment:
      prepend:
        - role: SYSTEM
          content: |
            # My Helpful Agent

            You are a bot that is supposed to help people.
```

6. Observe that warning logs in `ai-gateway` pod will stop being emitted and configuration will be applied
7. Send a request to the LLM provider API (see docs linked above) and observe that we now receive an error instead of a `404`

**Comment by zhengkezhou1** [comment]
assign

**Comment by zhengkezhou1** [comment]
This is a bit strange. I ran a setup test and found no issues with the transformation process.

Here's the successfully transformed Envoy configuration:

```
ai.policy.transformation.kgateway.io:
  '@type': type.googleapis.com/envoy.api.v2.filter.http.RouteTransformations
  transformations:
  - requestMatch:
      requestTransformation:
        logRequestResponseInfo: false
        transformationTemplate:
          mergeJsonKeys:
            jsonKeys:
              messages:
                tmpl:
                  text: |-
                    [{"content":"## My Helpful Agent

                    You are a bot that is supposed to help people.

                    ## Instructions

                    - Be nice
                    - Do other stuff","role":"system"},{{ join(messages, ", ") }}]
```

I also debugged with a breakpoint and confirmed that it's working as expected.

<img width="3764" height="1148" alt="Image" src="https://github.com/user-attachments/assets/ec87d7ee-7845-4118-bae4-0a3481238bdc" />

cc @npolshakova
