### ISSUE TITLE
policy: Support Policy deep merge for policy sub-fields

### ISSUE THREAD

**Issue by lgadban** [kgateway-dev/kgateway#11528]
Policy merging today works by merging the top-level fields (i.e. direct children of the policy spec) from the highest-priority to the lowest-priority policy. During this merge, the only strategy currently supported is to overwrite the lower-priority field with the higher-priority field if it is set.

The kgateway APIs (really TrafficPolicy) are monolithic-style APIs that may contain "sub-policies", e.g. [TrafficPolicy contains sub-policies](https://kgateway.dev/docs/reference/api/#trafficpolicyspec) of AI, transformations, ext-proc, etc.

As merging only considers the top-level field, this means the effective policy applied on a Route will not contain any sub-policy fields from a lower priority policy, even if the higher priority policy does not have it set.

A concrete example is with the transformation sub-policy. If this was applied on a TrafficPolicy attached to a Gateway:
```
spec:
  transformation:
    response:
      set:
      - name: x-kgateway-response
        value: '{{ request_header("x-kgateway-request") }}' 
```

but an HTTPRoute had this attached:
```
spec:
  transformation:
    request:
      set:
      - name: x-kgateway-request
        value: 'foo' 
```

The end result for the route would only have the HTTPRoute-specific request transformation added while the response transformation at the Gateway would be blown away.

The policy merging functionality should be updated to allow for sub-policies to handle their merging in a "deep merge" way
