### ISSUE TITLE
Weight based route precedence not working

### ISSUE THREAD

**Issue by djannot** [kgateway-dev/kgateway#11522]
### kgateway version

2.1.0-main

### Kubernetes Version

v1.30.8

### Describe the bug

I have the 2 following child HTTPRoutes:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-important
  namespace: {{ vars.httpbin_namespace }}
  annotations:
    kgateway.dev/route-weight: "1"
  labels:
    delegation.kgateway.dev/label: httpbin
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /hostnames
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /hostname
    backendRefs:
    - name: httpbin2
      port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-less-important
  namespace: {{ vars.httpbin_namespace }}
  labels:
    delegation.kgateway.dev/label: httpbin
spec:
  rules:
  - matches:
    - path:
        type: Exact
        value: /hostnames/host1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /hostname
    backendRefs:
    - name: httpbin1
      port: 8000
```

So when sending a request to `/hostnames/host1`, the request should be sent to `httpbin2`.

But it sent to `httpbin1` (which is more specific, but is part of an HTTPRoute with a lower weight).

Also, in https://github.com/kgateway-dev/kgateway/blob/main/internal/kgateway/translator/gateway/testutils/inputs/route-sort-weighted.yaml#L19 the weights should be strings, not integer.

### Expected Behavior

The request should be sent to `httpbin2`.

### Steps to reproduce the bug

Resources provided in the description
