### ISSUE TITLE
AuthConfig CR validation allows configs to be null

### ISSUE THREAD

**Issue by antonioberben** [kgateway-dev/kgateway#5636]
**Describe the bug**
Applying an `AuthConfig` with `configs: null` as attribute make gloo to crash. The CRD validation should not allow this scenario.

**To Reproduce**
1. Deploy gloo  (tested with `1.7.7` and `1.9.3`)
2. Apply following resource:

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  labels:
    argocd.argoproj.io/instance: agt-backend
  name: agt-backend-auth-plugin
  namespace: gloo-system
spec:
  configs: null
```

4. `glooctl check` shows the error then later.

**Expected behavior**
When the user applies the resource, the validation throw an error.

The solution is to add `required` in the `AuthConfig CRD` field to the attribute as the picture shows:
![config-crd](https://user-images.githubusercontent.com/5262332/143436059-4adc084f-7fa8-4f59-8aed-2cba5cef0373.png)

**Additional context**
- Gloo Edge version: `1.7.7` and `1.9.3`
