### ISSUE TITLE
Ability to specify external Redis, including redis options

### ISSUE THREAD

**Issue by jmunozro** [kgateway-dev/kgateway#5955]
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

I would like to define all redis values from a single place, like:
```
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: crossplane-system
data:
  endpoint: MTcyLjI2rrLjIwOCdsds40
  password: MzUzOGI0YTYteMjFhYidsdsds00OWZiLWIwZTUtYzYxOTA2NTFjNDYy
  port: NjMdsr3OQ==
```

That would be possible if we were able to define the deployment env vars like:
```
  - name: REDIS_ENDPOINT
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: redis-credentials
  - name: REDIS_PORT
    valueFrom:
      secretKeyRef:
        key: port
        name: redis-credentials
  - name: REDIS_URL
    value: $(REDIS_ENDPOINT):$(REDIS_PORT)
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: redis-credentials
```

This is not possible because [customEnv](https://github.com/solo-io/gloo/issues/5954) is not currently working, but even if it were, there is no way to avoid the rendering of `REDIS_URL` and `REDIS_SOCKET_TYPE` in the chart, so the `customEnv` would be duplicating the ENV vars.

### Describe the solution you'd like

Something like this would be fine:
```
❯ diff 2-rate-limit-deployment.yaml 2-rate-limit-deployment_PATCHED.yaml
97c97
<             {{- else }}
---
>             {{- else if not .Values.global.extensions.glooRedis.external }}}}
117a118,120
>             {{- if .Values.global.extensions.rateLimit.deployment.customEnv }}
> {{ toYaml .Values.global.extensions.rateLimit.deployment.customEnv | indent 12 }}
>             {{- end }}
```

if `.Values.global.extensions.glooRedis.external` is set to true the default REDIS_URL and REDIS_SOCKET_TYPE dont get rendered, just to not have duplicate ENV vars defined.

In addition, the current way to specify an external redis is a little hacky, it would be nice to have a more natural way to specify an external redis server than this:
```
cat << EOF > values.yaml
redis:
  disabled: true
  service:
    name: redis.default.svc.cluster.local <------------- Your external server here
rateLimit:
  deployment:
    customEnv:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-own-secret
            key: redis-password 
global:
  extensions:
    glooRedis:
      enableAcl: false
EOF
```

### Additional Context

https://github.com/solo-io/gloo/issues/5954
https://github.com/solo-io/gloo/issues/5879
https://github.com/solo-io/gloo/issues/5841
