### ISSUE TITLE
Observability metrics for VS and Upstream will continue to report after object is removed

### ISSUE THREAD

**Issue by pippitt** [kgateway-dev/kgateway#6938]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

After adding metrics via helm values as described in https://github.com/solo-io/gloo/issues/3964, it was observed that upstreams or virtual services that are removed/delete will continue to report their last status.  Would expect the metrics to stop after the upstream or virtual service is deleted.

### Steps to reproduce the bug

Enabled VS and upstream metrics by setting the following helm-values.yaml file
```
gloo:
  settings:
    kubeResourceOverride:
      spec:
        observabilityOptions:
          configStatusMetricLabels:
            Upstream.v1.gloo.solo.io:
              labelToPath:
                name: '{.metadata.name}'
                namespace: '{.metadata.namespace}'
            VirtualService.v1.gateway.solo.io:
              labelToPath:
                name: '{.metadata.name}'
                namespace: '{.metadata.namespace}'
```
Add an upstream or VS.  Observe the metrics in prometheus.  Delete the upstream and/or VS. Metric will continue (either with 0/healthy or 1/unhealthy).

Current workaround for a deleted VS restart the gateway deployment and for a deleted upstream restart the gloo deployment.

### Expected Behavior

When a VS or upstream is removed the associated metric would cease.
