### ISSUE TITLE
Userinfo endpoint timeout returns 403

### ISSUE THREAD

**Issue by Ati59** [kgateway-dev/kgateway#7956]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

~~Using `userinfoUrl` option to get the user infos on an unavailable endpoint makes some unwanted `403` responses (not `401`), meaning that some curl will be answered `200` and some `403`.~~

Using `userinfoUrl` option to get the user infos, if the `requestTimeout` is reached the response code is `403` whereas `401`.

### Steps to reproduce the bug

- Installing GE + Keycloack to create valid access token
- Create an `AuthConfig` ~~with a dummy URL (unavailable endpoint)~~ :
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: accesstoken-auth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      accessTokenValidation:
        jwt:
          remoteJwks:
            url: http://172.18.5.2:8080/realms/master/protocol/openid-connect/certs
        userinfoUrl: http://172.18.5.2:8080/realms/master/protocol/openid-connect/userinfo
```
- Use it on your favourite VS
- Define a very low `requestTimeout` (like 1ms) to be sure to reach the timeout

- To test :
```
export ACCESS_TOKEN=$(curl -L -X POST "${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" \
-H 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode "client_id=${client}" \
--data-urlencode 'grant_type=password' \
--data-urlencode "client_secret=${secret}" \
--data-urlencode 'scope=openid' \
--data-urlencode 'username=user1' \
--data-urlencode 'password=password' | jq -r .access_token)
curl -k -I -H "Authorization: Bearer $ACCESS_TOKEN" --resolve httpbin.domain.local:443:$(kubectl get svc -n gloo-system gateway-proxy -o yaml|yq ".status.loadBalancer.ingress[0].ip") https://httpbin.domain.local/get
```

<img width="1712" alt="snap" src="https://user-images.githubusercontent.com/35342300/224776439-e2a1777b-52ec-4919-897d-e04162d6cefa.png">

### Expected Behavior

~~It should return only `200` if token is valid or `401` if not whatever the userinfo endpoint availability~~
It should return `401` even if the userinfo endpoint timeout is reached

### Additional Context

On the customer context, we were looking at the userinfo endpoint availability and we also looked at the `requestTimeout` parameter. When I reproduced locally, I used the dummy URL to simulate it and I just realised that if the endpoint is unavailable at all, responses were sometimes succeeding, sometimes failing. The behaviour is then not normal and we guess that the customer is just facing this, out of their userinfo endpoint availability or the latency to get to it.

**Comment by jackstine** [comment]
[keycloak.zip](https://github.com/solo-io/gloo/files/11479229/keycloak.zip)
here is my current keycloak set up.

**Comment by jackstine** [comment]
The issue here is that the request returns a `403` when the `requestTimeout` is expired. The client would like to return a `401` instead.

**Comment by jackstine** [comment]
The solution to this is to change the `statusOnError` to a `401` in [the Gloo Settings CR](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#settings).

**Comment by jackstine** [comment]
The problem is now redefined as, the behavior defers from an userinfo endpoint unavailability to an userinfo endpoint timeout. It should behave the same way in both case.

The problem is not that the return status is `403`, this was misunderstood as a result of the above not occurring.

- If the userinfo endpoint is unavailable (like with dummy URL), GE will let the request gets to the route/upstream and forward the response, meaning the request was accepted even if the user data could not be retrieved.
- If the userinfo endpoint response is too long (meaning t > requestTimeout), GE will respond with a 403 meaning that the request did not get through (whereas the token is valid).

The issue with that is that Envoy is responding when the timeout occurs, not the Ext-Auth Service
envoy makes a call to the ext-auth service
    ->. ext-auth runs for some time
envoy hits the timeout, and responds back to the user with error
    -> ext-auth finishes, and responds back to envoy
envoy does nothing because the request was timed out before

it seems that the client would like to add a timeout to ext-auth requests, and have envoy ignore its timeout, so that ext-auth service is handling the request entirely

I would like to know the following before we make steps to approach what solutions we should have ready for the client.
1. What is the objective of the client when the `userInfoUrl` is called? why is this important?
2. Why can't the client just increase the `requestTimeout` for the request?

**Comment by Ati59** [comment]
The customer saw others `403` cases using 2 IdP and a `boolExpr` like in this example : 
```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: plugin-auth
  namespace: gloo-system
spec:
  booleanExpr: keycloack1 || keycloack2
  configs:
    - name: keycloack1
      oauth2:
        accessTokenValidation:
          jwt:
            remoteJwks:
              refreshInterval: 60s
              url: >-
                http://k8s-keycloak-keycloak-a5c3fd5df0-71b8b8269a993871.elb.eu-west-1.amazonaws.com:8080/realms/master/protocol/openid-connect/certs
    - name: keycloack2
      oauth2:
        accessTokenValidation:
          jwt:
            remoteJwks:
              refreshInterval: 60s
              url: >-
                http://k8s-keycloak-keycloak-191037661a-415a49341ec1a4c9.elb.eu-west-1.amazonaws.com:8080/realms/master/protocol/openid-connect/certs
```

- AuthConfig with just keycloak1 - expired token from keycloak1 --> 401 Unauthorized
- AuthConfig with just keycloak2 - expired token from keycloak1 --> 401 Unauthorized
- AuthConfig with just keycloak2 - valid token from keycloak1 --> 401 Unauthorized
- AuthConfig with just keycloak2 - invalid token (ex: "Authorization: balbla") --> **403 Forbidden**
- AuthConfig with just keycloak2 - no token --> **403 Forbidden**
- AuthConfig with keycloak1||keycloak2 - expired token from keycloak1 --> **403 Forbidden**
- AuthConfig with keycloak2||keycloak1 - expired token from keycloak1 --> **403 Forbidden**

For this tests, I tried the `statusOnError` workaround and it does not work.

All those cases should return `401`
