### ISSUE TITLE
UpstreamGroup continues to send traffic to unhealthy upstream.

### ISSUE THREAD

**Issue by AkshayAdsul** [kgateway-dev/kgateway#8715]
### Gloo Edge Product

Open Source

### Gloo Edge Version

V1.13.6 (But encountered this in other versions as well)

### Kubernetes Version

v1.25

### Describe the bug

We have an UpstreamGroup where healthchecks are configured on Upstream. But UpstreamGroup continues to send traffic to unhealthy upstream. 

### Expected Behavior

Expectation is  that if the upstream is not healthy then upstream group will not route the request through that upstream.
But it seems that upstream group is not aware of the upstream health.

### Steps to reproduce the bug

1. Create 2 services eg 
kubectl create ns echo
kubectl -n echo apply -f https://raw.githubusercontent.com/solo-io/workshops/master/gloo-edge/data/echo-service.yaml
kubectl -n echo apply -f https://raw.githubusercontent.com/solo-io/workshops/master/gloo-edge/data/echo-v2-service.yaml
2. Create Upstream Group and Upstream as below
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    discovered_by: kubernetesplugin
  name: echo-echo-v2-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app: echo-v2
  healthChecks:
  - alwaysLogHealthCheckFailures: true
    eventLogPath: /dev/stdout
    healthyThreshold: 3
    httpHealthCheck:
      path: /health
    interval: 10s
    reuseConnection: false
    timeout: 10s
    unhealthyThreshold: 1
  kube:
    selector:
      app: echo-v2
    serviceName: echo-v2
    serviceNamespace: echo
    servicePort: 8080
  loadBalancerConfig:
    healthyPanicThreshold: 0
    ringHash: {}
```
-------
-------

```
apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: my-service-group
  namespace: gloo-system
spec:
  destinations:
  - destination:
      upstream:
        name: echo-echo-v1-8080
        namespace: gloo-system
    weight: 5
  - destination:
      upstream:
        name: echo-echo-v2-8080
        namespace: gloo-system
    weight: 5
```
    
  3. Update Virtual service configuration 
 ```
  routes:
    - delegateAction:
        ref:
          name: echo-routetable
          namespace: echo
      matchers:
      - headers:
        - name: :authority
          value: echo.solo.io
        prefix: /
```
       
4. Update Route Table config
```
spec:
  routes:
  - matchers:
    - headers:
      - name: :authority
        value: echo.solo.io
      prefix: /
    routeAction:
      upstreamGroup:
        name: my-service-group
        namespace: gloo-system
```
       
     
5.  Make one of the upstreams unhealthy( eg. scale deployment replica to 1 of echo app)

6.  Send traffic
for i in {1..10};
do
curl -H "Host: echo.solo.io" $(glooctl proxy url)/
done

7. Observe No healthy upstream errors on half the requests.

## Related Issues:

- https://github.com/solo-io/solo-projects/issues/5647
