### ISSUE TITLE
Gloo CORS support is broken

### ISSUE THREAD

**Issue by suyuee** [kgateway-dev/kgateway#8719]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v 1.15.1

### Kubernetes Version

v 1.27.3

### Describe the bug

The CORS policy in virtual host options do not add CORS headers like "Access-Control-Allow-Methods" to response. Would appreciate any help

Sample response (notice no cors headers)
```
curl -i $(glooctl proxy url)/d0 -XOPTIONS
HTTP/1.1 204 No Content
content-length: 10
content-type: text/plain
date: Tue, 26 Sep 2023 18:47:40 GMT
server: envoy

```

### Expected Behavior

When setting cors policy in virtual service, in request response (OPTIONS or other), there should be headers like allowed methods/origins/headers attached, but there aren't.

### Steps to reproduce the bug

1. install gloo with helm
2. apply these simple manifests: https://gist.github.com/suyuee/3f6bce4af74b5dcdf121c7ce3fb63c49
3. curl -i $(glooctl proxy url)/ -XOPTIONS or `curl -i $(glooctl proxy url)/d0`
4. notice no cors headers returned

### Additional Environment Detail

I have tried both on eks and minikube

**Comment by suyuee** [comment]
If someone can confirm this is indeed an issue, I can try to put up a fix

**Comment by phillycheeze** [comment]
This is also broken for us when using the `directResponseAction` config. I'm guessing that it bypasses settings the CORS headers in that scenario.

**Comment by DuncanDoyle** [comment]
You need to send a valid "Origin" header that matches the one configured in your CORS configuration to get back the CORS headers , e.g.:


```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: api-example-com
  namespace: gloo-system
  labels:
    app: httpbin
spec:
  virtualHost:
    domains:
    - 'api.example.com'
    routes:
    - matchers:
      - prefix: /httpbin/
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system 
      options:
        prefixRewrite: /
        cors:
          allowCredentials: true
          allowHeaders:
          - origin
          allowMethods:
          - GET
          - POST
          - OPTIONS
          allowOrigin:
          - http://api.example.com
          exposeHeaders:
          - origin
          maxAge: 1d
```

```
curl -v -H "Origin: http://api.example.com" -H "Access-Control-Request-Method: GET" -H "Host: api.example.com" -X OPTIONS http://api.example.com/httpbin/options
```

If you specify an `Origin` header that does not match a value listed in `allowOrigin`, the CORS headers will not be returned.
