### ISSUE TITLE
Make External Redis Configuration in the gloo-ee Helm chart mutable rather than hardcoded

### ISSUE THREAD

**Issue by edubonifs** [kgateway-dev/kgateway#8726]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Regarding our [docs](https://docs.solo.io/gloo-edge/1.7.23/guides/security/rate_limiting/enterprise/#redis) , external redistribution configuration is hardcoded to use the following secret named redis:
```
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: gloo-system
  labels:
    app.kubernetes.io/instance: redis
type: Opaque
data:
  redis-password: <base64_password>
  users.acl: <base64_access-control-list>
EOF
```

However, authentication to redis doesn't necessarily have to be done with a redis-password, mostly when we have customers working with different multi cloud environment, in which the connection to their redis instance can require a URL.

### Describe the solution you'd like

Our clients as asking for not having this redis secret hardcoded, but mutable as authentication to redis is not always done with users.acl and password

# Related Issues

- https://github.com/solo-io/solo-projects/issues/6404
