### ISSUE TITLE
Upstreams should allow spec.kube.serviceNamespace to be missing, and search for the service in the same namespace where Upstream is created

### ISSUE THREAD

**Issue by edubonifs** [kgateway-dev/kgateway#9089]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15

### Kubernetes Version

1.26

### Describe the bug

spec.kube.serviceNamespace field on Upstream CRD is not mandatory. However, when I create an Upstream with that field missing, I get the following warning:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-edu-httpbin-8000
  namespace: default
spec:
  discoveryMetadata:
    labels:
      app: not-in-mesh
      service: not-in-mesh
  kube:
    selector:
      app: not-in-mesh
    serviceName: httpbin
    servicePort: 8000
status:
  statuses:
    gloo-system:
      reason: "warning: \n  1 error occurred:\n\t* Upstream name:\"default-httpbin-8000\"
        \ namespace:\"default\" references the service \"httpbin\" which does not
        exist in namespace \"\"\n\n"
      reportedBy: gloo
      state: Warning
```

### Expected Behavior

It seems that when you don't specify serviceNamespace, this appears as empty, while it should look at the namespace in which the resource has been created

### Steps to reproduce the bug

Apply an Upstream with field spec.kube.serviceNamespace missing and check Upstream status
