### ISSUE TITLE
RouteTables should only report status about the resource itself

### ISSUE THREAD

**Issue by edubonifs** [kgateway-dev/kgateway#9157]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

We have had this request from more than one client, they would like for the status on one RouteTable to only show the status of this specific RouteTable, and not status from the proxy itself.

This would help a lot on troubleshooting, and I will place an example.

One of our customer had an Upstream with a malformed grpcJsonTranscoder Upstream:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: fips
  namespace: default
spec:
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: default
    servicePort: 8000
    serviceSpec:
      grpcJsonTranscoder:
        matchIncomingRequestRoute: true
        protoDescriptorBin: CucBCh9nb29nbGUvcHJvdG9idWYvdGltZ
```
If you just apply this Upstream, every RouteTable on gloo will complain because of this Upstream with this error:
```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *grpcjson.plugin:
            invalid route. Route Name: gloo-system_service-3dc-v1-http-to-https-route-0-matcher-0;
            Route Error: ProcessingError. Reason: *grpcjson.plugin: invalid route.
            Route Name: gloo-system_service-3dc-v1-http-to-https-route-0-matcher-1;
            Route Error: ProcessingError. Reason: *grpcjson.plugin: invalid route.
            Route Name: gloo-system_service-3dc-v1-virtualservice-route-0-matcher-0\n\n"
          reportedBy: gloo
          state: Rejected
```

Even if there is no RouteTable referencing it, so it makes it difficult to troubleshoot. 

### Describe the solution you'd like

What the customer would like to see is the be able to see the status on the proxy on the proxy it self, and each RouteTable only containing the status of this specific RouteTable, for example:
```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy-edge-external_gloo-system':
          reportedBy: gloo
          state: Accepted
        '*v1.Proxy.gateway-proxy_gloo-system':
            invalidDestinations:                                                           # Only applicable on this specific route
              - reason: DestinationNotFound                                                # Typed reason
                description: *v1.Upstream { gloo-system.tst2-spar-web-8080 } not found     # Could be used in alerts
                matcher:
                - <copy-of-matchers-entry>
          reportedBy: gloo
          state: Warning
```

# Related Issues:

- [x] https://github.com/solo-io/gloo/issues/9160
