### ISSUE TITLE
Exposing the OpenTelemetry Environment Resource Detector in Gloo-Edge

### ISSUE THREAD

**Issue by sadieleob** [kgateway-dev/kgateway#9267]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.x

### Is your feature request related to a problem? Please describe.

Customer asked us to raise an RFE for exposing the [OpenTelemetry Environment Resource Detector](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/tracers/opentelemetry/resource_detectors/v3/environment_resource_detector.proto#extension-envoy-tracers-opentelemetry-resource-detectors-environment) 

Also, to expose the service_name field in the [OpenTelemetry tracer proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opentelemetry.proto.html)

### Describe the solution you'd like

They are in the process of integrating with a third-party distributed tracing backend (Cisco Cloud Observability) and noticed their spans are missing some resource metadata since we cannot set the OTEL_RESOURCE_ATTRIBUTES and have it consumed from Envoy.

The current config we saw in the envoy dump was:

```
tracing
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      '@type': type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      grpc_service:
        envoy_grpc:
          cluster_name: otel-collector-otlp-grpc_meg-system-dev01
```

They are looking to have:

```
tracing
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
       grpc_service:
         envoy_grpc:
           cluster_name: otel-collector-otlp-grpc_meg-system-dev01
       service_name: tag-envoy
       resource_detectors:
         - name: envoy.tracers.opentelemetry.resource_detectors.environment
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.tracers.opentelemetry.resource_detectors.v3.EnvironmentResourceDetectorConfig
```
