### ISSUE TITLE
GQL - 503 when using an unknown resolver 

### ISSUE THREAD

**Issue by asayah** [kgateway-dev/kgateway#9643]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

latest

### Kubernetes Version

v 1.27

### Describe the bug

this produce a 503: 

```
apiVersion: graphql.gloo.solo.io/v1beta1
kind: GraphQLApi
metadata:
  name: userdata
  namespace: gloo-system
spec:
  options:
    logSensitiveInfo: true
  executableSchema:
    executor:
      local:
        enableIntrospection: true
        resolutions:
          getUserdataa:  # <- note typo
            restResolver:
              request:
                headers:
                  :method: GET
                  :path: /userdata?id={$args.id}
              upstreamRef:
                name: default-userdata-80
                namespace: gloo-system

    schemaDefinition: |
      type Query {
        getUserdata(id: Int!): [Userdata] @resolve(name: "getUserdata")
      }

      type Userdata {      
        id: Int
        profilepicId: String
        country: String
        lang: String
      }


```

### Expected Behavior

it should throw a validation error, not a 503

### Steps to reproduce the bug

see above
