### ISSUE TITLE
Upstream HealthCheck httpHealthCheck port_value

### ISSUE THREAD

**Issue by ghost** [kgateway-dev/kgateway#9728]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.16.17

### Is your feature request related to a problem? Please describe.

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/upstream_health_checks/

The Upstream health check is default to the same service port in the upstream (80). But we expose the health-check endpoint in different port (9000)

```
  healthChecks:
    - healthyThreshold: 1
      interval: 15s
      timeout: 10s
      unhealthyThreshold: 0
      httpHealthCheck:
        path: /actuator/health/liveness
  kube:
    serviceName: my-service-name
    serviceNamespace: my-namespace
    servicePort: 80
```

### Describe the solution you'd like

Can we support the `port_value` in `httpHealthCheck` the same as envoy is doing here

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-endpoint-healthcheckconfig

<img width="612" alt="image" src="https://github.com/solo-io/gloo/assets/44228656/e613d624-f747-4ca7-9e54-1183d048e8e9">
