### ISSUE TITLE
Improving output formatting with Additional printer columns

### ISSUE THREAD

**Issue by find-arka** [kgateway-dev/kgateway#9782]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17.0

### Is your feature request related to a problem? Please describe.

Currently, when we run `kubectl get portal <object>` the output only shows the Name and Age columns. User would have to do an `-o yaml` to read the Status and related Message if any.

### Describe the solution you'd like

It would be nice to use [Additional Printer Columns](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns) and print more meaningful info. 
e.g. If we edit the `portals.portal.gloo.solo.io` CRD and add the following-
```yaml
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    - name: Status
      type: string
      description: The status of the Portal object
      jsonPath: .status.common.State.approval
    - name: Message
      type: string
      description: Message related to the status
      jsonPath: .status.common.State.message
```
then the `kubectl get` output becomes more meaningful e.g.

```bash
NAME     AGE   STATUS    MESSAGE
portal   11m   WARNING   reference grant missing for cross namespace references from (Portal: gloo-system.portal) to (ApiProduct: bookinfo.bookinfo-api)
```

Tested with the CRD changes, and without any changes and the output varies like the following-
![output](https://github.com/user-attachments/assets/bd94ca91-0ec9-46eb-8563-ecdeedc55efd)

### Describe alternatives you've considered

`-o yaml` and some `yq` queries are the only alternatives that I can think of.
