### ISSUE TITLE
Ability to populate "pathParameters"

### ISSUE THREAD

**Issue by htech7x** [kgateway-dev/kgateway#9864]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.7

### Is your feature request related to a problem? Please describe.

Ability to populate "pathParameters" (which is always null)

Example:
If in AWS API GW path resource named "/hello/{name}" deployed to stage named "v1" and called "/v1/hello/Alex", then APIGW event would look like:
```
{
  "resource": "/hello/{name}",
  "path": "/hello/Alex",
  "httpMethod": "GET",
  ...
  "pathParameters": {
    "name": "Alex"
  },
  ...
}
```
and I might reference that in my app lambda code like:
```
func handleRequest(_ context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	name := request.PathParameters["name"]
    ...
}
```
The closest to get to replicating this using extractors is setting a config like this for RouteTable:
```
- matchers:
    - regex: /v1/hello/[^\/]+
  options:
    timeout: 10s
    transformations:
      requestTransformation:
        transformationTemplate:
          extractors:
            name:
              header: :path
              regex: (/v1/hello/([^?]*).*)
              subgroup: 2
          headers:
            name:
              text: '{{ name }}' 
```
And then getting an event like this, where "id" header's value could be used:
```
{
    "resource": "/v1/lambda/Alex",
    "path": "/v1/lambda/Alex",
    "httpMethod": "GET",
    "headers": {
        ":authority": "auth.test.com",
        ":method": "GET",
        ":path": "/v1/lambda/Alex",
        ":scheme": "https",
        "name": "Alex",
        ...
    }
    ...
    "pathParameters": null,
    ...
} 
```

So it would be nice to be able to use the extractor value to populate "pathParameters" (which is always null) instead of having to update the lambda code to something like:

```
func handleRequest(_ context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
    # name := request.PathParameters["name"]
	name := request.Headers["name"] 
    ...
}
```
