### ISSUE TITLE
HTTPRoute with invalid extensionRef still allows requests

### ISSUE THREAD

**Issue by timflannagan** [kgateway-dev/kgateway#9963]
Note: Legacy issue but still relevant for the 2.x codebase post-CNCF donation

---

### Gloo Edge Product

Open Source

### Gloo Edge Version

main

### Kubernetes Version

1.29

### Describe the bug

When defining an HTTPRoute that configures an extensionRef to a non-existent custom filter, Gloo will bubble up this error to the HTTPRoute's status, but requests to the route will return 200s. This violations the documented spec for the [HTTPRoute API](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRouteFilter):
> If a reference to a custom filter type cannot be resolved, the filter MUST NOT be skipped. Instead, requests that would have been processed by that filter MUST receive a HTTP error response.
This can lead to undesired fail open behavior.

### Expected Behavior

Gloo should continue populating the HTTPRoute status correctly, but also replace routes with a 500 response to meet the documented extensionRef spec.

### Steps to reproduce the bug

You can reproduce locally using a main branch image, or following the GG project quickstart documentation:

1. ci/kind/setup-kind.sh; make kind-build-and-load-standard
2. helm upgrade -i -n gloo-system gloo _test/gloo-1.0.0-ci1.tgz --create-namespace --set kubeGateway.enabled=true --set global.image.variant="standard"
3. k create ns httpbin && kubectl -n httpbin apply -f https://raw.githubusercontent.com/solo-io/gloo-mesh-use-cases/main/policy-demo/httpbin.yaml
4. kubectl apply -f reproducer.yaml
5. kubectl port-forward deployment/gloo-proxy-http -n gloo-system 8080:8080 &
6. curl -i localhost:8080/headers -H "host: www.example.com"

Here's the reproducer.yaml configuration I was applying:

<details>

```yaml
---

kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
  namespace: gloo-system
spec:
  gatewayClassName: gloo-gateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  hostnames:
  - "www.example.com"
  parentRefs:
  - name: http
    namespace: gloo-system
  rules:
  - backendRefs:
    - name: httpbin
      port: 8000
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.solo.io
        kind: RouteOption
        name: non-existent-ref

---

apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: foo
  namespace: gloo-system
spec:
  options:
    retries:
      retryOn: 'connect-failure'
      numRetries: 3
      perTryTimeout: '5s'
    timeout: 10s
```

</details>

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208170054530874) by [Unito](https://www.unito.io)
